infinyon/fluvio

src/cli/src/spu/custom/mod.rs
src/cli/src/spu/custom/register.rs
src/cli/src/spu/custom/unregister.rs
src/client-rs/src/sc.rs
src/sc-api/src/api_key.rs
src/sc-api/src/flv_register_custom_spus.rs
src/sc-api/src/flv_unregister_custom_spus.rs
src/sc-api/src/lib.rs
src/sc-api/src/public_api.rs
src/sc-core/src/services/public_api/flv/mod.rs
src/sc-core/src/services/public_api/flv/register_custom_spus_req.rs
src/sc-core/src/services/public_api/flv/unregister_custom_spus_req.rs
src/sc-core/src/services/public_api/mod.rs
src/sc-core/src/services/public_api/public_server.rs

@sehz I ran `cargo fmt`, which produced several changes in addition to the renaming `custom-spu` (issue #5). If you would prefer that I do not run `cargo fmt`, happy to force push a reversion.
`cargo test` runs successfully.

rename custom-spu commands to register and unregister; run cargo fmt

---

src/cli/src/cluster/install/local.rs
src/cli/src/cluster/install/mod.rs

fixes #36 cl- updated description
- updated launching SPU statement
- display log locations for SC and SPU for local

CLI cluster install changes

---

k8-util/helm/fluvio-sys/templates/local-pv.yaml
k8-util/helm/fluvio-sys/templates/storage.yaml
k8-util/helm/fluvio-sys/values.yaml

Attempt to resolve #28 
This works on minikube, but I think on cloud platforms we need to have `nodeAffinity` match some label we give to nodes that have sufficient storage and are capable of running SPU.
Is there any way to define run shell commands to be run on the nodes, so that we may create a separate dir for SPU data and set its permissions? My current changes use `/tmp` because I don't know of a way to create a new dir and set permissions on it.
Do we need to write a provisioner for this? Or use something like https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/provisioner.md

Add Local Persistent Volume option for fluvio-sys Helm chart

---

.gitignore
Cargo.lock
src/cli/Cargo.toml
src/cli/build.rs
src/cli/src/root_cli.rs

This implements #86, adding additional information to the `fluvio version` command. The added info that gets printed includes:
* Current git hash when `cargo build` is invoked
* OS version info (as reported by `uname -a`)
* Rustc version info
The new output for the version command looks like this:
```
$ fluvio version
Fluvio version : 0.6.0
Git Commit     : d3bd95af2e2cd02997f948181681719e530ab98e
OS Details     : Linux thinkpad 5.7.8-100.fc31.x86_64 #1 SMP Thu Jul 9 15:16:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Rustc Version  : 1.45.0-nightly
```
---
* I've branched this PR starting from the commit 69ec1e6 because commit fb92e83 introduces a build error for the `cli` crate.
* By using `uname -a` for OS info I may have made it platform-dependent (unless Windows users are using cygwin). …

Add more detailed information in `fluvio version` command

---

src/cli/build.rs

```
$ flvd version
Fluvio version : 0.6.0
Git Commit     : f2f09621aa759bde1ab0371c3cdffa293c211d7f
OS Details     : Darwin 19.5.0 x86_64
Rustc Version  : 1.46.0-nightly (daecab3 2020-07-10)
```

Fixed retrieval of OS information for macos

---

Cargo.lock
src/cli/Cargo.toml
src/cli/src/cluster/install/k8.rs

Fixes #119 
-  check if helm is installed and is right version.
- If helm is not installed, I am displaying an error.
- If version is <3.2.0, It is showing a warning to install a compatible version.
- For version comparsion/checking , I have used `semver` library.

Added changes for pre-flight check before cluster install

---

src/cli/src/cluster/install/helm.rs
src/cli/src/cluster/install/k8.rs

Fixes #128 
- Added logic to check if compatible sys chart is installed(0.1.0)
- Also checking if the sys chart is not installed at all.

Check if compatible sys chart is installed

---

src/cli/src/cluster/install/k8.rs
src/cli/src/cluster/install/local.rs
src/cli/src/cluster/install/mod.rs
src/cli/src/lib.rs
src/cli/src/profile/cli.rs
src/cli/src/tls/mod.rs
src/client-rs/src/config/config.rs
src/client-rs/src/config/tls.rs

As I was reading through the codebase getting ready for the profiles work, I noticed that there was a lot of inconsistency regarding `TlsConfig`s, including many repeated definitions and representations. I took some time to try to organize it a little bit better. Here are some of the major points:
* Renamed all instances of `TlsConfig` in the `cli` crate to `TlsOpt` in order to avoid naming confusion
* Separated `TlsConfig` enum from `client-rs` (with variants `NoVerification`, `File`, and `Inline`) into two separate enums:
* `TlsConfig` enum with variants `NoVerification` and `WithCerts` is the "most canonical" representation of a TlsConfig, where the `WithCerts` variant carries the inline certs.
* `TlsConfigPaths` enum with variants `NoVerification` and `WithPaths` is one step removed …

Refactor TlsConfig

---

src/event-stream-k8/src/dispatcher/k8_ws_service.rs
src/event-stream-k8/src/dispatcher/mod.rs

Allow create/update spec and status directly without going thru dispatcher.

expose k8_ws_service in event-stream-k8

---

src/cli/src/consume/mod.rs
src/cli/src/custom/list.rs
src/cli/src/custom/register.rs
src/cli/src/custom/unregister.rs
src/cli/src/group/create.rs
src/cli/src/group/delete.rs
src/cli/src/group/list.rs
src/cli/src/lib.rs
src/cli/src/partition/list.rs
src/cli/src/produce/mod.rs
src/cli/src/profile/context.rs
src/cli/src/profile/k8.rs
src/cli/src/profile/sync/cloud/login_agent.rs
src/cli/src/profile/sync/cloud/mod.rs
src/cli/src/spu/list.rs
src/cli/src/topic/create.rs
src/cli/src/topic/delete.rs
src/cli/src/topic/describe.rs
src/cli/src/topic/list.rs
src/client-rs/src/client/client.rs
src/client-rs/src/client/cluster.rs
src/client-rs/src/config/cluster.rs
src/client-rs/src/config/config.rs
src/client-rs/src/lib.rs
tests/runner/src/tests/smoke/consume.rs
tests/runner/src/tests/smoke/produce.rs

This is part of my cleaning up the codebase surrounding `TlsConfig` in preparation for adding TLS support.
This PR:
* Removes the duplication between `client-rs/config::Cluster` and `client-rs/config::cluster::ClusterConfig` by removing `Cluster` and making `ClusterConfig` the default.
* Makes `ClusterClient` in charge of "connecting" itself using a `ClusterConfig, rather than forcing `ClusterConfig` to know how to do that. `ClusterConfig` is just a data structure now.

Refactor ClusterConfig and ClusterClient

---

src/cli/src/lib.rs
src/cli/src/profile/context.rs
src/cli/src/profile/k8.rs
src/cli/src/tls/mod.rs
src/client-rs/src/client/cluster.rs
src/client-rs/src/config/cluster.rs
src/client-rs/src/config/config.rs
src/client-rs/src/config/tls.rs
src/client-rs/test-data/tls/file.toml
src/client-rs/test-data/tls/inline.toml
src/client-rs/test-data/tls/no-verf.toml

Previously, there was a mix of types that represented different TLS options, which made things less ergonomic and more confusing. For example:
* To not use TLS, you'd use `None::<TlsConfig>`
* To use TLS but without domain verification, you'd use `Some(TlsConfig::NoVerification)`
* To use TLS with verification, you'd use `Some(TlsConfig::WithCerts)`
I found the mix of the `Option` type into this scheme rather confusing, so I flattened it out and created some nice `From` implementations to make things more streamlined.
Now, at the top level we have `TlsPolicy`, which can be
* `Disabled`: meaning TLS is not used
* `NoVerify`: meaning that TLS is used but the certificates are not verified
* `Verify(TlsConfig)`: meaning that TLS is used and certificates are verified.
The presence of a …

Consolidate TLS configuration options

---

k8-util/docker/fluvio/Makefile

Looks like this file was not saved and committed along with the other make fluvio image changes; This PR now adds the binaries for both spu server and sc k8 server and targets the correct `Dockerfile.fluvio` image. Fixes https://github.com/infinyon/fluvio/runs/1038457585?check_suite_focus=true

ensure dockerfile is correctly named and binaries are copied

---

src/cluster/src/install.rs

I noticed that if a Fluvio installation got partially created and then cancelled, then when it tried to resume it would fail because `kubectl` would be installing secrets that already exist. This causes the installation to first try to delete secrets (ignoring if they don't exist), and then re-installing them.

Fix kubectl secret panic

---

src/cli/src/consume/cli.rs
src/cli/src/consume/fetch_log_loop.rs
src/cli/src/lib.rs
src/client/src/client/cluster.rs
src/client/src/consumer.rs
src/client/src/error.rs
src/client/src/lib.rs
src/client/src/offset.rs
src/client/src/params.rs
tests/runner/src/tests/smoke/consume.rs

This PR introduces a new API for Offsets that makes it impossible to construct illegal `Offset` values. This renames the previously-named `FetchOffset` into just `Offset`. The `Offset` type is essentially an enum with private variants, achieved by wrapping an `OffsetInner` enum inside the `Offset` struct with a private field. This makes it impossible for users to manually construct an Offset, they must use the validating constructors `Offset::absolute`, `Offset::from_beginning`, and `Offset::from_end` which only optionally produce an `Offset` when the argument is valid. This creates the invariant that if an `Offset` type exists, it is valid (e.g. there are no negative offsets).
Additionally, this PR renames `FetchLogOption` to `ConsumerConfig` since it is used both in fetching and …

Add better Offset API

---

.github/workflows/publish_latest_chart.yml

Helm is unable to install charts with a version field that does not conform to semver.

Publish helm charts with semantic versioning

---

Cargo.lock
src/cli/Cargo.toml
src/cli/src/cluster/minikube.rs
src/cluster/Cargo.toml

Fixes `fluvio cluster set-minikube-context` so that it:
- Only tries to update `/etc/hosts` when the `minikubeCA` does not match `minikube ip`
- Does not create duplicate entries in `/etc/hosts` when it does need to update.

Only update /etc/hosts when necessary. Prevent duplicate /etc/hosts entries

---

src/cluster/src/error.rs

I noticed that the cluster crate's error type uses `fluvio_futures::io::Error` which is just a very roundabout re-export of `std::io::Error`. I imagine it was incorrectly added by IDE inference. Better to depend directly on `std::io::Error`.

Fix cluster IO import to std::io

---

.github/workflows/ci.yml
Makefile
src/cli/src/cluster/install/mod.rs
src/cli/src/lib.rs
src/cluster/src/install.rs
src/sc/src/k8/mod.rs
src/spu/src/start.rs
tests/runner/src/cli.rs
tests/runner/src/main.rs
tests/runner/src/test_runner.rs
tests/runner/src/tests/smoke/produce.rs

fix issue when panic during futures task on sc.  it seems that running 1 hour delay can panic.  reduce sleep time to 60 seconds which seems to be done the trick.
Instead of waiting using heuristics waits, actual status are used for waiting for provisioning
- local and k8 spus
- topics
Also, cancel is applied for all workflows

fix futures timer issue on k8 by using smaller wait period

---

action.yaml
dev-tools/action-install-fluvio-cluster.sh
dev-tools/action-install-minikube.sh
dev-tools/ci-replace-helm.sh

This PR adds a composite github action for re-use in github workflows.
To use this github action in another workflow, you should be able to use the following:
```yaml
...
- name: Install Fluvio Local Cluster
uses: infinyon/fluvio@latest
- name: Check Fluvio Installation
run: |
fluvio --help
```
We'll need to tag release once merged and publish to the github actions market place.
Not sure if we want to lock the version of the github action with the version of fluvio. I am using `latest` in the example above, and in the action.sh script it will always build from the fluvio repo master branch source.

add install fluvio github composite action

---

Cargo.lock
src/cli/src/cluster/install/k8.rs
src/cluster/Cargo.toml
src/cluster/src/check.rs
src/cluster/src/error.rs
src/cluster/src/install.rs

This adds better error messages to the `helm` client in such a way that it bubbles all the way up to the CLI. Before, if `helm` was not installed, if the user ran `fluvio cluster install`, they would be given the following error:
```bash
$ fluvio cluster install
error: No such file or directory (os error 2)
```
Now, it gives this error:
```bash
$ fluvio cluster install
error: Unable to find 'helm' executable
Please make sure helm is installed and in your PATH.
See https://helm.sh/docs/intro/install/ for more help
```
In addition, this PR makes the cluster installer attempt to fix some things if the precheck runs into errors:
- If fluvio-sys is not installed, it attempts to install it
- If the minikube context is not set right, it will set it

Streamline cluster install

---

src/dataplane-protocol/src/error_code.rs
src/dataplane-protocol/src/record.rs

I was seeing a weird thing in CI where sometimes this lint would fail a build and sometimes not. I fixed it just so it's not a problem in the future.
This basically switches a few spots to using the [`matches!`](https://doc.rust-lang.org/beta/std/macro.matches.html) macro, which I just learned about. It's kinda neat!

Fix obscure clippy lint

---

Cargo.lock
Cargo.toml
examples/00-echo/Cargo.toml
examples/00-echo/src/main.rs
src/cli/Cargo.toml
src/cli/src/consume/fetch_log_loop.rs
src/client/Cargo.toml
src/client/src/consumer.rs
src/client/src/lib.rs
src/client/src/sync/controller.rs
src/cluster/Cargo.toml
tests/runner/Cargo.toml
tests/runner/src/tests/smoke/consume.rs

Implements #365 
This incorporates the changes from the `fluivo-socket` crate where `AsyncResponse` now implements `Stream`. It's important to note that `AsyncResponse` streams batches of records. The wrapper code in the consumer API is able to flat_map those batches into records so that consumers just see a nice record type. Basic consumer code will now look like this:
```rust
let mut stream = consumer.stream("my-topic", 0).await?;
while let Some(Ok(record)) = stream.next().await {
if let Some(bytes) = record.try_into_bytes() {
let string = String::from_utf8_lossy(&bytes);
println!("Got record: {}", string);
}
}
```
Right now, I'm not able to get the smoke tests to work, but I'm also not sure if that's due to my changes or not. You can try out the changes by checking out the `stream` …

Consumer api

---

.github/workflows/ci.yml

Upgrade `manusa/actions-setup-minikube` to the latest version.
Removes the following warnings caused by [CVE-2020-15228](https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w):
```
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
Relates to:
- https://github.com/manusa/actions-setup-minikube/issues/22
- …

chore: Upgrade actions-setup-minikube to v2.0.1

---

Cargo.lock
src/cli/src/cluster/install/mod.rs
src/cli/src/custom/list.rs
src/cli/src/custom/register.rs
src/cli/src/custom/unregister.rs
src/cli/src/group/create.rs
src/cli/src/group/delete.rs
src/cli/src/group/list.rs
src/cli/src/partition/list.rs
src/cli/src/spu/list.rs
src/cli/src/topic/create.rs
src/cli/src/topic/delete.rs
src/cli/src/topic/describe.rs
src/cli/src/topic/list.rs
src/client/Cargo.toml
src/client/src/client/cluster.rs
src/cluster/src/install.rs
tests/runner/src/test_runner.rs
tests/runner/src/tests/smoke/produce.rs

I thought I had merged this before but apparently not. With recent changes to `fluvio-socket`, we no longer require `&mut Fluvio` in order to create an admin instance, it can be relaxed to `&Fluvio`. This PR updates the client to reflect this and bumps the version to `0.2.1`.

Relax mut in admin

---

Cargo.lock
src/cli/Cargo.toml
src/cli/src/bin/main.rs
src/cli/src/error.rs
src/cli/src/root_cli.rs

This uses the `external_subcommand` feature of clap/structopt in order to try to find and pass arguments to subcommands. For any subcommand `foo`, if `fluvio foo` is not a built-in subcommand, it will search the user's `PATH` for an executable named `fluivo-foo`. If it finds one, it will execute it, passing all subsequent arguments to it. In other words, if `fluvio-foo` exists and a user invokes `fluvio foo one two three -- four five`, then fluvio will execute `fluvio-foo one two three -- four five`

Add external subcommand execution to fluvio-cli

---

Cargo.lock
src/dataplane-protocol/Cargo.toml
src/sc/Cargo.toml
src/spu/Cargo.toml
src/storage/Cargo.toml
src/storage/src/error.rs

Related to issue #411.
Update to use latest fluvio socket 0.2.0 and remove unnecessary dependencies

update to use fluvio-socket 0.2.0

---

Makefile
src/cli/Cargo.toml
src/client/Cargo.toml
src/client/src/admin.rs
src/client/src/client/client.rs

Cherry pick from rbac branch which set `native_tls` as default feature for client. 
This avoid issue with use of AllFluvioSocket

make native-tls as default

---

Makefile
src/cli/src/cluster/install/mod.rs
tests/runner/src/test_runner.rs

Add more stabilities to CI by add wait time in couple of places which are configurable.
Cause of CI failure likely to be that CI VM are often throttle down due to oversubscribed host machine.

make CI more stable

---

src/cli/src/partition/list.rs

Fixes #431 
Fixed output for `fluvio partition list`
Now the output is shown as:
```
$ fluvio partition list 
No partitions found
```

Listing partitions on an empty system

---

src/cli/src/cluster/install/k8.rs

Fixes #375 
Using local repository for chart location when we run `fluvio cluster install --sys --develop`

Use local repository to install sys chart when --develop is used

---

install.sh
src/cli/src/http.rs
src/cli/src/install/mod.rs
src/cli/src/install/plugins.rs
src/cli/src/install/update.rs
src/package-index/src/http.rs
src/package-index/src/lib.rs

This makes the bootstrapping script automatically install the fluvio-cloud plugin by invoking `fluvio install` after installing the Fluvio CLI. This PR also introduces changes that make the install subcommand "bootstrap aware", and format its output printing style to match the bootstrap script's. Specifically, if it detects a `FLUVIO_BOOTSTRAP` environment variable is set, it will prepend `fluvio: ` to each line of output. The full install flow now looks like this:
```
fluvio: ⏳ Downloading Fluvio 0.6.0-alpha.4 for x86_64-apple-darwin...
fluvio: ⬇️ Downloaded Fluvio, installing...
fluvio: ✅ Successfully installed ~/.fluvio/bin/fluvio
fluvio: ☁ Installing Fluvio Cloud...
fluvio: 🎣 Fetching latest version for package: fluvio/fluvio-cloud...
fluvio: ⏳ Downloading package with latest version: …
```

Add fluvio-cloud install to bootstrapping script

---

src/cli/src/http.rs

This prevents the duplicate DNS resolution on the URL for http requests in the CLI.

Fix CLI http address

---

Cargo.lock
src/cli/src/install/plugins.rs
src/cli/src/install/update.rs
src/package-index/Cargo.toml
src/package-index/src/error.rs
src/package-index/src/lib.rs
src/package-index/src/target.rs

This causes `Target::from_str` to interpret `"x86_64-unknown-linux-gnu"` as `Target::X86_64UnknownLinuxMusl`, and replaces `fluvio_index::PACKAGE_TARGET` constant with `fluvio_index::package_target()` function to return a folded and structured version of the current build's target.

Index target

---

Cargo.lock
src/cli/Cargo.toml
src/cli/src/install/mod.rs
src/cli/src/install/plugins.rs
src/cli/src/install/update.rs
src/package-index/Cargo.toml
src/package-index/src/error.rs
src/package-index/src/http.rs
src/package-index/src/lib.rs
src/package-index/src/package_id.rs
src/package-index/src/target.rs

The `PackageId` type from `fluvio-package-index` was somewhat finicky in that it always carried the package version as an `Option<Version>`, because it could be written in a string like either:
```
<group>/<name>:<version>
OR
<group>/<name>
```
This made some code surrounding PackageId somewhat unweildy because we always had to unwrap the option whenever we wanted to use the Version, even in a context where we knew that we had already checked that we had the version available.
---
This PR changes that type to have two different typed variants, `PackageId<WithVersion>` and `PackageId<MaybeVersion>`. The `PackageId<MaybeVersion>` behaves essentially the same way that the old `PackageId` did. However, the new `PackageId<WithVersion>` type guarantees that it will always have a Version …

Package id types

---

.github/workflows/ci.yml

Now that we are skipping checks in CI, I am re-enabling minikube tunnel.

Enabling minikube tunnel in the CI

---

.github/workflows/ci.yml
Cargo.lock
Makefile
src/client/Cargo.toml
src/client/src/client/cluster.rs
src/client/src/consumer.rs
src/client/src/producer.rs
src/client/src/spu/spu_pool.rs
src/client/src/sync/store.rs

Currently, in the Fluvio Client, SPU Pool are automatically initialized when client is created even thought it may not needed until producer and consumer are created.  With this PR, pool are lazy initialized when producers or consumers requested it.
In addition, SPU pool are shared using Arc rather than directly which allows drop trait work correctly.
The skip checks are disabled for test

lazy load spu pool in the client

---

.github/workflows/ci.yml
Makefile

Fix smoke tests for running TLS with policy.  This was broken by changes to CLI refactoring.
Skip uninstalling in the CI
Add option to make release image for k8

Fix tls test

---

.github/workflows/ci.yml
Makefile

Use musl target for running k8 smoke test in CI.
This remove need to build 2 different targets

Optimize musl

---

Cargo.lock
install.sh
src/cli/Cargo.toml
src/cli/src/install/mod.rs
src/cli/src/install/plugins.rs
src/cli/src/install/update.rs
src/cli/src/root_cli.rs

Search $FLUVIO_DIR and $HOME/.fluvio/extensions for extension executable

---

Cargo.lock
tests/runner/src/main.rs
tests/runner/src/tests/smoke/produce.rs

Smoke test can hang if there is panic inside spawn.
This PR add panic handler in the main to ensure panic is handled correctly

test CI not handling panic correctly

---

src/spu/src/controllers/leader_replica/leader_controller.rs

SPU leader controller is supposed to have reconciliation loop timer with 60 seconds but due to logic bug, is only wait for first loop leading to log exhaustion

Fix leader controller with zero reconciliation loop timer

---

src/cli/src/profile/mod.rs
src/cli/src/profile/sync/mod.rs
src/cli/src/root_cli.rs
src/cluster/src/extension/group/mod.rs
src/cluster/src/extension/mod.rs
src/cluster/src/extension/releases.rs
src/cluster/src/extension/spu/mod.rs
src/extension-consumer/src/topic/mod.rs
src/extension-runner-local/src/run/mod.rs

These are some small wording changes on the structopt docstrings which change the way the help menu is rendered for the CLI. I changed it so that everything is using the imperative tone, e.g. "Read" rather than "Reads". This is also how the descriptions will be written for the CLI reference on the website.

Make CLI help menu wording consistent

---

src/cli/src/install/mod.rs
src/cli/src/lib.rs

Closes #532 also deals with the edge case where [`code`](https://doc.rust-lang.org/std/process/struct.ExitStatus.html#method.code) doesn't return a status code because it's been killed on a unix system (my version of fluvio-package segfaulted due to a `SIGSEGV`).

Handle nonexistent extensions dir and extension signals.

---

src/cli/src/bin/main.rs
src/cli/src/lib.rs

Fixes help for subcommands and sub-options (this might not be the right word) such as `fluvio profile help`

Fixed help for fluvio subcommands

---

actions/action-install-fluvio-cluster.sh

Yesterday in standup we discussed if there was any advantage to having the composite action in it's own repo and couldn't find a good one. This fixes fluvio cluster installer when you're not in the [root of the fluvio repo](https://github.com/infinyon/fluvio-client-node/pull/36/checks?check_run_id=1517989280).

Fix composite action when not in fluvio repo

---

src/cli/src/profile/delete_profile.rs

This fixes the wording of a warning on the `fluvio profile delete` command when deleting the current profile.
Previously, it said
> warning: this removed your current profile, use `config switch-profile to select a different one
which was missing a `'` and also referencing an outdated command. The fixed message is
> warning: this removed your current profile, use 'fluvio profile switch' to select a different one

Fix warning for fluvio profile delete

---

Cargo.lock
src/package-index/Cargo.toml
src/package-index/src/package_id.rs

This fixes an itty bitty bug that I found having to do with the `fluvio install` command.
When running something like `fluvio install fluvio/fluvio-cloud`, I get this output:
```
🎣 Fetching latest version for package: fluvio/fluvio-cloud:...
⏳ Downloading package with latest version: fluvio/fluvio-cloud:0.1.0...
🔑 Downloaded and verified package file
```
This is _almost_ what we want, except there is a trailing `:` after the `fluvio/fluvio-cloud` on the first line of output
This is because the `Display` impl of `PackageId<MaybeVersion>` was _just barely_ wrong. So I fixed it and added a test to make sure it prints as expected. Now we have:
```
🎣 Fetching latest version for package: fluvio/fluvio-cloud...
⏳ Downloading package with latest version: fluvio/fluvio-cloud:0.1.0...
🔑 Downloaded …
```

Fix Display impl for PackageId<MaybeVersion>

---

Cargo.lock
Cargo.toml
k8-util/minikube/reset-docker.sh
k8-util/minikube/reset-minikube.sh
src/controlplane-metadata/src/partition/replica.rs
src/dataplane-protocol/Cargo.toml
src/dataplane-protocol/src/record.rs
src/extension-consumer/src/produce/mod.rs
src/sc/src/controllers/partitions/controller.rs
src/sc/src/controllers/partitions/reducer.rs
src/sc/src/services/private_api/private_server.rs
src/sc/src/services/public_api/watch.rs
src/spu/Cargo.toml
src/spu/src/controllers/leader_replica/leader_controller.rs
src/spu/src/controllers/sc/dispatcher.rs
src/spu/src/core/store.rs
src/storage/src/checkpoint.rs
src/storage/src/mut_records.rs
src/stream-dispatcher/src/dispatcher/k8_dispatcher.rs
src/stream-model/Cargo.toml
src/stream-model/src/store/dual_store.rs
src/stream-model/src/store/k8.rs
tests/produce-large.sh

With changes in topic delete, SC is sending out unnecessary replicate updates to SPU again.
This happens because SC's private services is listening to partition metadata changes in addition to spec changes. However, whenever status changes, metadata changes are triggered because it's revision id is changed as well.
In this PR, metadata changes are no longer trigger by changing K8's revision id.
In addition, SPU replica changes's delete status is computed from either deleted time stamp or delete status.  This insures that delete flag is only depends on metadata changes not Partition's delete status

fix regression in updates from SC to SPU

---

Cargo.lock
src/cli/Cargo.toml
src/cli/src/install/mod.rs
src/cli/src/install/plugins.rs
src/cli/src/install/update.rs

Closes #617.
The error was caused by the fact that I was directly opening the executable's current file and trying to write to it. This fix causes the updater to write the update to a new temporary file, then `rename` that file to the path of the original executable. The original executable remains available on disk for as long as the executing process needs it, but the path becomes inhabited by the newly updated executable immediately. On unix this is actually an atomic operation, so at no point is there an inconsistent state (e.g. if some process tried to execute `fluvio` while we were halfway through writing it before).
This PR is rebased on top of #603 so that I could test the musl build on a docker ubuntu image. We can either merge #603 first or merge this one to supersede it.

Fluvio self update using rename

---

src/cli/src/install/mod.rs

`std::fs::rename` relies on the source and destination filesystems being the same. This falls apart if, say `/tmp` is mounted on a different partition. This change switches to use `std::fs::copy`, which works no matter the fs setup. Since our temp file is being created inside a `tempfile` (from tempfile crate), then the temp directory and contained files will be cleaned up no matter what.

Fix self-update when /tmp is mounted on a different fs

---

makefiles/Github.toml
makefiles/Pi.toml

This is a fix to deal with non-forced releases as seen like this one https://github.com/infinyon/fluvio/actions/runs/449824310.
Let's wait until we're ready for another release before we merge this.

Used script over command in cargo-make

---

Cargo.lock
src/cli/src/profile/mod.rs
src/cli/src/profile/rename.rs
src/client/Cargo.toml
src/client/src/config/config.rs

Closes #542 
Adds a new CLI command:
```
fluvio profile rename <from> <to>
```
which renames a profile called `from` to a new profile called `to`. If the old profile name was marked as the current profile, the "current profile" name will be updated to match the renamed profile, so this command will not change any other behavior.

Add 'fluvio profile rename' to rename profiles

---

Cargo.lock
src/cli/Cargo.toml
src/extension-consumer/Cargo.toml
src/extension-consumer/src/topic/create.rs

This is a quick-and-dirty fix that closes #535 by simply rejecting `fluvio topic create` for non-alphanumeric topic names.
Now, upon using a non-alphanumeric name, you receive this error:

Fix topic names

---

Cargo.lock
src/cli/Cargo.toml
src/cli/src/profile/view.rs

Closes #639 
```
❯ cargo run --bin fluvio -- profile view
PROFILE   CLUSTER   ADDRESS          TLS
*  minikube  minikube  10.97.5.40:9003  Disabled
❯ rm -rf ~/.fluvio
```
Then, what happened Before:
```
❯ cargo run --bin fluvio -- profile view
Error:
0: Fluvio client error
1: Fluvio config error
2: No such file or directory (os error 2)
```
What happens After:
```
❯ cargo run --bin fluvio -- profile view
Unable to find Fluvio config
Try using 'fluvio cloud login' or 'fluvio cluster start'
```

Prevent 'fluvio profile view' from error with missing config

---

Cargo.lock
src/extension-consumer/Cargo.toml
src/extension-consumer/src/topic/create.rs

This relaxes the constraint for creating topic names from alphanumeric-only to be valid for valid hostnames.

Fix topic name validation

---

.github/workflows/ci.yml

I don't know if there is specific reason we did not have this here before, but it makes CI faster when you can cancel the previous and queued jobs when you push to a branch. To make this work, we need to add a `GITHUB_TOKEN` secret

Add 'cancel previous runs' to CI

---

src/spu/src/config/spu_config.rs
src/storage/src/config.rs
src/storage/src/fixture.rs
src/storage/src/index.rs
src/storage/src/lib.rs
src/storage/src/mut_records.rs
src/storage/src/range_map.rs
src/storage/src/replica.rs
src/storage/src/segment.rs
src/storage/tests/replica_test.rs

Implement an option of flush policy of flushing every n writes, default is still to flush every write, unit test coverage tests other cases. Issue #37

Implement flush on counted writes from #37

---

Cargo.lock
Cargo.toml
k8-util/helm/fluvio-app/Chart.yaml
k8-util/helm/fluvio-app/templates/sc-deployment.yaml
k8-util/helm/fluvio-app/templates/sc-public.yaml
k8-util/helm/fluvio-app/templates/spu-k8-config.yaml
k8-util/helm/fluvio-app/values.yaml
src/cli/Cargo.toml
src/cluster/Cargo.toml
src/cluster/src/cli/start/k8.rs
src/cluster/src/cli/start/mod.rs
src/cluster/src/delete.rs
src/cluster/src/start/k8.rs

* allow arbitrary helm values to when starting cluster.
* add `--chart-values` option to CLI
* add `annotations`,`securityContext`,`podSecurityContext` to helm chart values

helm: support arbitary annotations

---

src/client/Cargo.toml
src/client/src/consumer.rs
src/client/src/lib.rs

This makes infinyon/fluvio-client-node#66 much cleaner and it will also help with our rust client users.

Made consumer module pub

---

.github/workflows/publish_crates.yml

I'm I read https://github.com/katyo/publish-crates correctly, I think this can actually work on every push of master without error and will work on all the projects in the workspace?
@sehz can you add a `CARGO_REGISTRY_TOKEN` to the settings with a token from crates.io?

Github actions for crates publishing

---

examples/02-echo/Cargo.toml

Pretty sure that this is due to rust-lang/cargo#8157. Basically, `cargo run` within the `examples/02-echo` directory vs running `cargo run --bin echo` outside said directory.

add attributes feature async-std in echo example

---

Cargo.lock
src/spu/src/config/spu_config.rs
src/storage/Cargo.toml
src/storage/src/config.rs
src/storage/src/lib.rs
src/storage/src/mut_records.rs
src/storage/src/records.rs

https://github.com/infinyon/fluvio/issues/37
With a delay flush policy set, writes will cause a flush after the set delay
time.
Clusters of writes with an interarrival time below the delay will not incur
extra flushes, a final flush is scheduled after the latest write.
The delay flush task will exit after associated mut_records instance is
dropped
TOREVIEW: the get_file method was commented out for removal because the
ownership seemed convoluted to resolve (?) even with a sharing in place
for the f_sink file. the get_file method in the FileRecords trait never
seemed to be used in the codebase
This is a good way to inspect a couple of different cases:
RUST_LOG=debug cargo test test_write_records_idle_delay

Implement flush policy to flush on a delay time after writes

---

k8-util/helm/fluvio-app/templates/sc-public.yaml
src/sc/src/k8/operator/spg_operator.rs
src/sc/src/k8/operator/spu_k8_config.rs
src/storage/src/mut_records.rs

Remove hard coded `external_local_traffic` from SPU service spec.  Instead make it configurable thru helm template

further k8 svc customization

---

src/client/Cargo.toml
src/client/README.md

The stuff on https://crates.io/crates/fluvio says `flv-client` and doesn't have any keywords or categories. I chose the category slug of `database` because it seemed the least-not-wrong.
* [According to the cargo docs, each category should match one of the strings available](https://doc.rust-lang.org/cargo/reference/manifest.html#the-categories-field) at https://crates.io/category_slugs.

Updated Readme and cargo.toml to be more accurate for crates.io

---

Cargo.lock
src/stream-model/Cargo.toml
src/stream-model/src/core.rs
src/stream-model/src/epoch/dual_epoch_map.rs
src/stream-model/src/lib.rs
src/stream-model/src/store/dual_store.rs
src/stream-model/src/store/k8.rs
src/stream-model/src/store/metadata.rs

Fixed bug where stale data was allowed to write to cache event thought their rev was outdated.
This could happens when there are rapid state changes and cache didn't caught up.
This makes store to be idempotent

fix metadata store updating logic

---

CHANGELOG.md
Cargo.lock
action.yaml
examples/01-consume/src/main.rs
examples/02-echo/src/main.rs
src/auth/Cargo.toml
src/cli/Cargo.toml
src/client/Cargo.toml
src/client/src/consumer.rs
src/cluster/Cargo.toml
src/controlplane-metadata/Cargo.toml
src/controlplane-metadata/src/topic/spec.rs
src/controlplane/Cargo.toml
src/dataplane-protocol/Cargo.toml
src/dataplane-protocol/src/batch.rs
src/dataplane-protocol/src/record.rs
src/extension-common/Cargo.toml
src/extension-consumer/Cargo.toml
src/extension-consumer/src/consume/logs_output.rs
src/sc-schema/Cargo.toml
src/sc/Cargo.toml
src/spu-schema/Cargo.toml
src/spu/Cargo.toml
src/storage/Cargo.toml
src/storage/src/mut_records.rs
src/storage/src/segment.rs
tests/runner/Cargo.toml
tests/runner/src/tests/smoke/consume.rs

~This is dependent on https://github.com/infinyon/fluvio-protocol/pull/4 but I've written the refactor using a work around.~
Depends on https://github.com/infinyon/fluvio-protocol/pull/5
We should also probably rename `try_into_bytes` to `bytes`. 
Record updates:
* Added `AsRef` implementation `as_ref()` returns `&[u8]`
* `to_utf8_lossy` (returns a string)
* `to_bytes` takes ownership and returns a `Vec<u8>`
* `impl TryFrom<Record> for String`

Remove optional in DefaultAsyncRecord.

---

.github/workflows/release.yml
Makefile

We have been experiencing build breakages because the fluvio-cluster installer always assumes that for any version of `fluvio-app`, there will be an equivalent version of `fluvio-sys`, but our release.yml currently does not always push them together. This adds a make task and a CI step to always push fluvio-sys with fluvio-app at the same version number.

Add helm-publish-sys to Makefile and release CI

---

src/cluster/src/cli/check.rs
src/cluster/src/cli/mod.rs
src/cluster/src/cli/start/k8.rs
src/cluster/src/cli/start/local.rs
src/cluster/src/cli/start/sys.rs
src/cluster/src/lib.rs
src/cluster/src/start/k8.rs
src/cluster/src/start/local.rs
src/cluster/src/sys.rs

This should fix the remaining CI breakage. The problem was that `SysConfig` was being used in the `cli/check` module but had not been updated since `chart_version` was made into a required field, causing the "missing chart_version" error we were seeing before.
Do we want to force publish over `0.7.0-alpha.2` for this or bump to `0.7.0-alpha.3`?

Add missing chart_version to SysConfig in check

---

README.md
src/client/README.md

- Adds badges to `fluvio` README so that they appear on crates.io
- Centers badges on front README and makes badge styles consistent
- Update README wording to emphasize "real-time applications"
- Add quick links to send people to the website
[Rendered](https://github.com/infinyon/fluvio/blob/ff43abf9efa4e73d295df0d85106550fb0142453/README.md)

Update Fluvio client README and front README

---

src/client/src/consumer.rs
src/client/src/lib.rs

There have been some API changes that broke some doc tests. For some reason it was not picked up by CI, I will open an issue to make sure doctests are run in CI. This fixes broken doc tests from consumer. This can be verified by running `cargo test --doc`.

Fix broken doc tests in consumer

---

src/cli/src/install/mod.rs
src/cli/src/install/plugins.rs
src/cli/src/install/update.rs
src/package-index/src/lib.rs

Closes #704 
This adds a `--develop` flag to the `fluvio update` and `fluvio install` commands. When this flag is _not_ provided, these commands will look for the latest release version of the package. When `--develop` is provided, these commands will search for the latest pre-release versions. Note that this will change the default behavior of these commands, since right now they will always find the latest pre-release version. Another thing to note is that this means that the `curl | bash` install script will only ever be able to install release versions since we cannot pass command-line options to the curl'd script. I think this is the behavior we actually want, I just wanted to point it out.

Fluvio update

---

Cargo.lock
src/cli/Cargo.toml
src/client/Cargo.toml
src/client/src/client/cluster.rs
src/client/src/error.rs
src/client/src/lib.rs
src/cluster/Cargo.toml
src/extension-consumer/Cargo.toml

This change adds a `MINIMUM_PLATFORM_VERSION` constant to the client crate and causes it to check the platform version of the cluster it is communicating with. If the cluster's platform version is below the minimum, then the client will produce a new `FluvioError::MinimumPlatformVersion` error and refuse to connect.
I believe that we may want to have a bigger design discussion about this. I think it's possible that the solution here is rather brittle, since a future protocol change may change the offsets of data and the position of `platform_version` in the message may not be reliable, making this change useless. We probably want to think about creating a stable encoding of the _protocol_ version in such a way that is very future compatible and which can be checked by clients and servers …

Protocol compatibility for Fluvio client

---

Cargo.lock
src/cluster/Cargo.toml

@sehz so we can publish to crates.io

Set fluvio-cluster back to 0.7.0 since it was not pushed to crates

---

src/cli/src/lib.rs

Closes #540 
The `fluvio version` command will now print the name of the profile that it used when asking the cluster for its platform version
```
$ fluvio version
Fluvio CLI      : 0.7.0-alpha.3
Fluvio Platform : 0.7.0-alpha.2 (minikube)
Git Commit      : 5bd790b4712c538f67311a0d56177f877915061e
OS Details      : Darwin 20.3.0 x86_64
Rustc Version   : 1.49.0 (e1884a8 2020-12-29)
```

Add profile name printout beside platform_version

---

Cargo.lock
src/cluster/Cargo.toml
src/command/Cargo.toml
src/command/src/lib.rs

If `Command::new(...).result()?` fails with a nonzero exit code, the CommandError type will now capture the stdout and stderr values and render them in the Display of the error type. This will make it easier to debug problems that occur from exit codes of invoked commands.

Updates CommandExt to capture stdout and stderr in error types

---

Cargo.lock
src/cluster/Cargo.toml
src/cluster/src/check/mod.rs
src/cluster/src/cli/error.rs

Closes #541 
This adds a suggestion to the fluvio-cluster CLI telling the user to try deleting the cluster and trying again when this happens.
```
❯ cargo run --bin fluvio -- cluster start --local
Performing pre-flight checks
✅ ok: Supported helm version is installed
✅ ok: Supported kubernetes version is installed
✅ ok: Kubernetes config is loadable
✅ ok: Fluvio system charts are installed
Error:
0: Failed to install Fluvio locally
1: Kubernetes client error
2: client error: 409 Conflict
Suggestion: Run `fluvio cluster delete --local`, then retry
```

Suggest deleting cluster on start failure

---

Cargo.lock
src/cli/Cargo.toml
src/cli/src/lib.rs

Closes #364 
This is a CLI-only change that just causes the `fluvio version` command to check OS details at runtime rather than compile time.

OS version at runtime

---

.github/workflows/ci.yml
src/cluster/src/start/k8.rs

increase FLV_CLUSTER_MAX_SC_NETWORK_LOOP, VERSION check count to higher to make it K8 run reliable

make k8 CI run more reliable

---

src/cluster/src/check/mod.rs

This code was part of an experiment to locate existing SC and SPU processes on a local machine so we could detect if a cluster was already running. I had meant to remove it from a previous PR and forgot. The only harm it does is printing junk to stdout, it was not impacting CI beyond that.
As a note on the progress of this feature, I was having a difficult time figuring out a good cross-platform way of getting this done, and I'm still not 100% sure that this is the right way to approach this anyways. We can discuss alternate potential options later if this continues to be a problem.

Remove unfinished 'local cluster exists' check

---

src/cluster/src/error.rs
src/cluster/src/start/k8.rs

Adds
```
debug!(
platform = %version,
chart_version = %self.config.chart_version,
"Existing platform version is different than chart version",
);
```
and
```
#[error("Expected to find cluster with platform version {0}")]
FailedPlatformVersion(String),
```

Add debug and reword error message for install

---

Cargo.lock
src/auth/Cargo.toml
src/auth/src/error.rs
src/auth/src/x509/authenticator.rs
src/cli/Cargo.toml
src/client/Cargo.toml
src/client/src/config/config.rs
src/client/src/error.rs
src/dataplane-protocol/Cargo.toml
src/extension-common/src/lib.rs
src/extension-consumer/Cargo.toml
src/extension-consumer/src/error.rs
src/sc/Cargo.toml
src/service/Cargo.toml
src/socket/Cargo.toml
src/socket/src/error.rs
src/socket/src/stream.rs
src/spu/Cargo.toml
src/storage/Cargo.toml

A little while ago I made the mistake of turning a bunch of error types into struct-variants. This makes it very difficult to pattern match on errors when we need to inspect them. I would like to change them back to being tuple-variants.
Updating the error enums is a breaking change, so I will open this PR now, and we can either merge it right away or we can wait until we are already ready to do a version bump on a few crates and we can include this in those changes.
The main motivation behind doing this is that it will make implementing things like https://github.com/infinyon/fluvio/issues/580 much easier

Change error types back to tuples

---

.github/workflows/ci.yml
.github/workflows/composite_action.yml

Closes #563.
Based on the comments in https://github.com/actions/toolkit/issues/399, it seems that there's currently no way to remove the red X from the builds using the continue-on-error flag. So, this seems to be the best way to do it.

Move composite action to new workflow file

---

.github/workflows/ci.yml
Cargo.lock
src/dataplane-protocol/src/error_code.rs
src/spu/src/config/spu_config.rs
src/spu/src/controllers/follower_replica/state.rs
src/spu/src/controllers/leader_replica/replica_state.rs
src/spu/src/core/storage/mod.rs
src/spu/src/services/public/produce_handler.rs
src/storage/Cargo.toml
src/storage/src/batch.rs
src/storage/src/batch_header.rs
src/storage/src/bin/cli.rs
src/storage/src/checkpoint.rs
src/storage/src/config.rs
src/storage/src/error.rs
src/storage/src/fixture.rs
src/storage/src/index.rs
src/storage/src/lib.rs
src/storage/src/mut_index.rs
src/storage/src/mut_records.rs
src/storage/src/range_map.rs
src/storage/src/records.rs
src/storage/src/replica.rs
src/storage/src/segment.rs
src/storage/src/validator.rs
src/storage/tests/replica_test.rs

Limit batch size to 1M as default.   SPU will now reject attempts to write the `RecordSet` if any of the batch size exceed limit.

implement limit for batch size

---

src/extension-consumer/src/consume/fetch_log_loop.rs

This solves half of #678 regarding the CLI consumer. If the stream is closed, the CLI will print a message saying so.
I am working on figuring out how to solve a similar problem on the producer side of things. It is slightly trickier with the producer because it seems like the producer (currently) does not keep an open connection that we can watch to see if it goes down. I will have to play with the setup to figure out the best way to do that.

Add CLI message when consumer stream closes

---

Cargo.lock
src/cli/Cargo.toml
src/cli/src/bin/main.rs
src/cli/src/error.rs
src/cli/src/lib.rs

Closes #580 
This adds graceful error handling to `fluvio topic create` (if a named topic already exists) and to `fluvio topic delete` (if the named topic does _not_ already exist).
Topic create used to look like this:
```
❯ cargo run --bin fluvio -- topic create foobar
Error:
0: Consumer Error
1: Fluvio client error
2: Fluvio SC schema error
3: Received error code: TopicAlreadyExists (Some("topic \'foobar\' already defined"))
```
Topic create now looks like:
```
❯ cargo run --bin fluvio -- topic create foobar
topic "foobar" created
❯ cargo run --bin fluvio -- topic create foobar
Topic already exists
```
Topic delete now looks like this:
```
❯ cargo run --bin fluvio -- topic delete foobar
Topic not found
```
One thing I added here is a new error variant: `CliError::ExitWithCode`. It is …

Cli error printout

---

src/cluster/src/cli/start/k8.rs
src/cluster/src/start/k8.rs
src/sc/build.rs
tests/runner/src/environment/k8.rs

Closes #790.
This fixes an error that would occur when updating the `VERSION` file. There were actually two problems in play:
- The new test runner was not applying development options
- The build.rs script for fluvio-sc was not rebuilding the SC with the updated VERSION.
Both of these problems are fixed in this PR. The first one is fixed by adding a `.development()` method to the fluvio-cluster builder so that development options will be consistent in the various places it is used.

Fix tests. Push develop mode into fluvio-cluster

---

Cargo.lock
src/cli/src/lib.rs
src/client/src/consumer.rs
src/extension-consumer/Cargo.toml
src/extension-consumer/src/consume/fetch_log_loop.rs
src/extension-consumer/src/consume/logs_output.rs
src/extension-consumer/src/consume/mod.rs

This closes #397 
- Simplify CLI consumer
- Reduce dependency of CLI consumer on the internal details of API consumer
- Enhance API consumer with any required information

Use public consumer API for CLI consumer

---

src/types/Cargo.toml

I think #769 should have bumped the patch version (or maybe even the minor) because this adds some new functionality that the client crate relies on.

bump types version

---

src/service/Cargo.toml

After staring at `cargo tree` for a while and removing all the path dependencies in the dependencies (to test out publishing), I finally figured out that `fluvio-service` in the repo has `fluvio-socket` with `0.6.0` but the [published version of `fluvio-service` uses `0.5.0` for `fluvio-socket](https://crates.io/crates/fluvio-service/0.4.0)` and this breaks a bunch of stuff.

Bumped patch version to publish

---

Cargo.lock
src/client/Cargo.toml
src/client/src/config/cluster.rs

Recently, the `FluvioConfig` field called `addr` was renamed to `endpoint`. This caused a backwards incompatible change because new clients could no longer communicate with an old version of Fluvio Cloud. This fixes this incompatibility by adding a serde "alias = addr" to the endpoint field. This means that serde will deserialize the field from either "endpoint" OR "addr", but it will always serialize it as "endpoint". We will need to bump the client crate prerelease version for this to be useful.

Fix breaking change in config by adding serde alias

---

Cargo.lock
src/package-index/Cargo.toml
src/package-index/src/target.rs

This adds an associated constant `Target::ALL_TARGETS` which is a slice of all Target values. This is essentially used as an iterator over the variants of the Target enum, and is useful for cleaning up code in fluvio-packages.

Package index updates

---

install.sh

Closes #758 
This should be the last step in our migration to separating RELEASES from PRERELEASES. This PR updates the `install.sh` script to install the latest RELEASE version of Fluvio, as defined by `https://packages.fluvio.io/v1/stable`. The install script now has the following behavior:
- `curl -fsS https://packages.fluvio.io/v1/install.sh | bash` will install latest RELEASE version
- `curl -fsS https://packages.fluvio.io/v1/install.sh | VERSION=latest bash` will install latest PRERELEASE version
- `curl -fsS https://packages.fluvio.io/v1/install.sh | VERSION=x.y.z-alpha.w bash` will install version `x.y.z-alpha.w`

Update install script to install full releases

---

src/cli/src/install/plugins.rs
src/cli/src/install/update.rs

When updating the install script to use latest RELEASE version (#812), I noticed this odd side effect, which was that I was immediately prompted to update to a new version of Fluvio. This happened because the installer gave me the latest RELEASE but the update-checker saw that there was a PRERELEASE that was more recent. This PR updates the update-checker to only compare against the latest RELEASE version.
```
❯ ./install.sh
fluvio: ⏳ Downloading Fluvio 0.6.1 for x86_64-apple-darwin...
fluvio: ⬇️ Downloaded Fluvio, installing...
fluvio: ✅ Successfully installed ~/.fluvio/bin/fluvio
fluvio: ☁️ Installing Fluvio Cloud...
fluvio: 🎣 Fetching latest version for package: fluvio/fluvio-cloud...
fluvio: ⏳ Downloading package with latest version: fluvio/fluvio-cloud:0.1.4...
fluvio: 🔑 Downloaded …
```

Prompt for Fluvio update only for new release versions

---

Cargo.lock
src/extension-runner-local/Cargo.toml
src/spu/Cargo.toml
src/spu/src/controllers/follower_replica/state.rs
src/spu/src/controllers/leader_replica/leaders_state.rs
src/spu/src/controllers/leader_replica/replica_state.rs
src/spu/src/services/public/produce_handler.rs
src/storage/Cargo.toml
src/storage/src/batch.rs
src/storage/src/batch_header.rs
src/storage/src/error.rs
src/storage/src/lib.rs
src/storage/src/mut_records.rs
src/storage/src/range_map.rs
src/storage/src/replica.rs
src/storage/src/segment.rs
src/storage/src/validator.rs
src/storage/tests/replica_test.rs

Remove unneeded code.
Send batches and records as mutable references instead of own

Storage cleanup

---

action.yaml

This is required in order for other repos using our `action.yaml` to specify a pre-release version for testing against. E.g. fluvio-client-node.

Re-enable VERSION in GH action

---

Cargo.lock
src/cli/Cargo.toml
src/cli/src/lib.rs
src/cli/src/metadata.rs
src/cli/src/version.rs
src/cluster/Cargo.toml
src/extension-common/Cargo.toml
src/extension-common/src/lib.rs
src/extension-consumer/Cargo.toml
src/extension-consumer/src/consume/mod.rs
src/extension-consumer/src/partition/mod.rs
src/extension-consumer/src/produce/mod.rs
src/extension-consumer/src/topic/mod.rs

Previously, there was no easy way to see the versions of all installed fluvio subcommands. Now, `fluvio version` will detect and print the versions:
```
$ fluvio version
Fluvio CLI           : 0.7.1-alpha.0
Fluvio CLI SHA256    : cef57bc33d2f730815c6b458bbae07d70775af0e8c0f1d3139e66584a6f2f20d
Fluvio Platform      : 0.7.1-alpha.0 (local)
Git Commit           : 0662bfa5eec00aa3c42ca6aeb63b1d04632a0235
OS Details           : Darwin 11.2.2 (kernel 20.3.0)
=== Plugin Versions ===
package (fluvio-package)       : 0.1.4
cloud (fluvio-cloud)           : 0.1.4
```
Let me know if anybody has different preferences as to how these get printed. I'm starting to think that there's so much information getting packed into `fluvio version` that we might want to start printing it in a structured format by …

Show version for all subcommands

---

.github/workflows/release.yml

This is my best guess as to how to disable publishing install.sh. As always, this is hard to test without actually trying it out.
I used the `steps.if` key from the github workflow spec https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps

Do not release install.sh by default

---

Cargo.lock
src/cli/Cargo.toml
src/cli/src/install/mod.rs
src/cli/src/install/plugins.rs
src/cli/src/install/update.rs
src/cli/src/metadata.rs
src/cli/src/version.rs
src/extension-common/Cargo.toml
src/extension-common/src/lib.rs
src/extension-consumer/src/consume/mod.rs
src/extension-consumer/src/partition/mod.rs
src/extension-consumer/src/produce/mod.rs
src/extension-consumer/src/topic/mod.rs
src/package-index/Cargo.toml
src/package-index/src/http.rs
src/package-index/src/lib.rs
src/package-index/src/package_id.rs

Closes #672 
This updates the `fluvio update` command to behave as follows:
- `fluvio update` with no parameters will update the CLI and any plugins that support being updated* to the latest stable version
- `fluvio update <pluginA> <pluginB>` will update any of the named plugins to the latest stable version
- `fluvio update` with a `--develop` flag with update the targets to the latest prerelease (rather than stable)
In order to be compatible with auto-updating, each plugin must now provide a new field of metadata called `package`, which identifies the plugin on packages.fluvio.io. For example, the `fluvio-cloud` plugin would provide a package field containing `fluvio/fluvio-cloud`. This is delivered via the already-existing metadata mechanism, where any plugin executed with a `metadata` …

Make `fluvio update` update plugins as well as CLI

---

.github/workflows/publish_latest_fluvio.yml
.github/workflows/release.yml
makefiles/S3.toml

This PR adds new `cargo make` tasks for publishing Fluvio to the `latest` release channel, as well as a brand new workflow file that will trigger these tasks, `publish_latest_fluvio`. Here's a breakdown of the new tasks:
- `cargo make publish-fluvio-latest` will publish the current release build of Fluvio to `latest`
- FLUVIO_VESRION: `$(cat VERSION)+$(git rev-parse HEAD)`, e.g. `0.7.2-alpha.1+abcdef`
- `cargo make publish-fluvio` will publish the current release build of Fluvio to VERSION.
- `cargo make bump-fluvio-latest` will bump the `latest` version of Fluvio to the current VERSION+git hash
- Only if Fluvio has been published on all targets for that VERSION, e.g. in prior steps of the CI job.
- `cargo make bump-fluvio` will use FLUVIO_VERSION to bump the appropriate tag
- e.g. if …

Update CI to publish each commit to master

---

Cargo.lock
src/package-index/Cargo.toml
src/package-index/src/lib.rs

This is required for the latest `fluvio-package` release, which is required for setting up publish-on-merge CI for fluvio.

Use exact version equality (with build metadata) for package-index releases

---

Cargo.lock
src/auth/Cargo.toml
src/sc/Cargo.toml

Some of the changes from https://github.com/infinyon/fluvio/pull/856 need version bumps. If I read that PR right I think `fluvio-controlplane` may also need a version bump but I'm not sure.

Bump version of fluvio-auth to fix publishing of fluvio-sc

---

Cargo.lock
src/dataplane-protocol/Cargo.toml
src/dataplane-protocol/src/fetch/request.rs
src/dataplane-protocol/src/fetch/response.rs
src/dataplane-protocol/src/lib.rs
src/dataplane-protocol/src/produce/request.rs
src/dataplane-protocol/src/record.rs
src/protocol/Cargo.toml

In order to compile `dataplane-protocol` crate into WASM, we need to separate out I/O related code.

make  dataplane-protocol crate more modular

---

.github/workflows/publish_latest_fluvio.yml

Fixes #906 by explicitly setting the latest stable Rust toolchain. This fixes upstream dependencies on const generics

Explicitly use latest Rust toolchain

---

.github/workflows/release.yml

This is the same fix as the one we merged earlier this week, I just forgot to apply the same fix to all the workflows. I think this should be all we need in order for our workflows to always be using stable rust.

Fix release workflow with stable rust

---

CHANGELOG.md
Cargo.toml
src/spu/src/controllers/leader_replica/replica_state.rs
src/spu/src/controllers/sc/dispatcher.rs
src/spu/src/core/storage/mod.rs
src/storage/src/replica.rs

This fix issue where topic delete is not completed when SPU goes offline.
Steps to reproduce and test:
``` 
$ cargo build --bin fluvio
$ ./target/debug/fluvio start --local --develop
$ ./target/debug/fluvio topic create test
topic "test" created
```
```
$ ps -ef | grep fluvioubuntu
ubuntu   3733903       1  5 04:34 pts/0    00:00:00 /home/ubuntu/fluvio/target/debug/fluvio cluster run sc
ubuntu   3733913       1  0 04:34 pts/0    00:00:00 /home/ubuntu/fluvio/target/debug/fluvio cluster run spu -i 5001 -p     0.0.0.0:9010 -v 0.0.0.0:9011 --log-base-dir /tmp/fluvio
ubuntu   3733968 3622789  0 04:34 pts/2    00:00:00 grep --color=auto fluvio
$ kill -9 3733913
```
This will hang, so you have to press ^c
```
$ flvd topic delete  test
^c
Error: 
0: Fluvio client error
1: Fluvio socket error
2: …
```

Topic delete reconcillation

---

Cargo.toml
src/cluster/Cargo.toml
src/extension-common/Cargo.toml

To restore CI's build performance.
Revert back unnecessary dependency to pre-release crates due to workspace requirements

disable lto for now

---

.github/workflows/ci.yml

Local Mac cluster test is taking too long.  Disabling for now

disable mac local cluster test

---

src/cluster/src/delete.rs
src/cluster/src/error.rs
src/storage/src/mut_records.rs

I finally figured out why `fluvio cluster delete` was behaving weird but only sometimes. If `fluvio-sys` was installed, `fluvio cluster delete` works just fine. BUT, if `fluvio-sys` was not installed, then we would get a Kubernetes 404 during the uninstall step because we were attempting to interact with CRD objects that weren't there.
This is a quick fix that skips certain uninstall steps if fluvio-sys is not installed.

Fixed fluvio cluster delete when sys chart not installed

---

.github/workflows/ci.yml

to fix CI failure for running unit tests by increase SOCKET wait delay like cluster test

increase SOCKET DELAY for linux unit test

---

.cargo/config.toml
.github/workflows/ci.yml
.gitignore
Makefile

Alright, I managed to make some substantial breakthroughs in the last half of today. The entire CI workflow is now consistently using sccache and running in about 9-10 minutes end-to-end. I also managed to cut down on the workflow file by quite a lot by writing a single job that uses a matrix to test our different scenarios.
```yaml
tests:
name: ${{ matrix.make.name }} (${{ matrix.os }})
runs-on: ${{ matrix.os }}
strategy:
matrix:
os: [ubuntu-latest, macos-latest]
rust: [stable]
make:
- name: Clippy
task: "check-clippy"
- name: Unit tests
task: "build-all-test run-all-unit-test"
- name: Doc tests
task: "run-all-doc-test"
include:
- os: ubuntu-latest
sccache-path: /home/runner/.cache/sccache
- os: macos-latest
sccache-path: /Users/runner/Library/Caches/Mozilla.sccache
exclude:
- os: …
```

Fix sccache and rewrite CI jobs as a matrix

---

crates/fluvio-cluster/src/check/render.rs
crates/fluvio-cluster/src/cli/start/k8.rs
crates/fluvio-cluster/src/cli/start/local.rs
crates/fluvio-cluster/src/cli/start/mod.rs
crates/fluvio-cluster/src/render.rs
crates/fluvio-cluster/src/start/k8.rs
crates/fluvio-cluster/src/start/local.rs

This PR adds the change to not display the spinner in the CI. It can also be hidden from the cli with the --hide-spinner flag
Closes #1968

Do not display spinner in CI

---

crates/fluvio-cli/src/lib.rs
crates/fluvio-cluster/src/start/local.rs

During the local cluster start we check and do not create a new one if `CustomSpu` already exists. This allows to `resume` local after shutdown. So, one could do:
```
fluvio cluster start --local
//insert some data
fluvio cluster shutdown --local
//processes killed but metadata preserved
fluvio cluster start --local
//cluster started with existing metadata and data
```
Additionally, I changed the order of where to look up fluvio external command. Now, the same folder where the current executable is the first one. It is convenient for local development (you want fluvio-run from your workspace not in fluvio home dir) and for CI tasks where we use two versions of fluvio (stable and dev).

fix: check if custom spu exists on start

---

crates/fluvio-hub-util/src/fvm/mod.rs
crates/fluvio-version-manager/src/command/update.rs
crates/fluvio-version-manager/src/common/version_installer.rs

Uses `pkgset` over `version` for PackageSet contents file.

fix: use `pkgset` over `version`

---

crates/fluvio-spu/src/services/public/produce_handler.rs
tests/cli/fluvio_smoke_tests/producer-smartmodule.bats

Currently, errors related to SM on produce requests are not properly propagated to the Fluvio client. It leads to the produce request just hanging and is killed by timeout. This includes when smartmodule does not exist but is used in transformation.

fix: properly propagate sm errors on produce

---

crates/fluvio/src/config/cluster.rs

Remove unnecessary conversion in some tests to fix Clippy error.

fix: clippy warnings in tests

---

.github/workflows/ci.yml
crates/fluvio-hub-util/src/fvm/api/client.rs
crates/fluvio-hub-util/src/fvm/mod.rs
crates/fluvio-version-manager/src/command/install.rs
crates/fluvio-version-manager/src/command/update.rs
tests/cli/fvm_smoke_tests/fvm_basic.bats

Updates FVM internals, specifically the Hub Client, to use the new endpoint for fetching
Package Sets.
This change does not affect user facing state.

feat: update fvm to use new hub endpoints on fetch

---

.github/workflows/ci.yml
tests/cli/test_helper/tools_check.bash

Currently, if we use `nick-fields/retry` retries for cli tests it restarts the entire test suite on a failure. In PR we leverage `BATS_TEST_RETRIES` which allows to configure retries for an individual test which is more effective.

chore: use individual cli test retries

---

.github/workflows/cd_dev.yaml
.github/workflows/ci.yml
.github/workflows/hourly.yml
crates/fluvio-cli/src/profile/add.rs
crates/fluvio-cli/src/profile/list.rs
crates/fluvio-cluster/src/check/mod.rs
crates/fluvio-cluster/src/cli/delete.rs
crates/fluvio-cluster/src/cli/diagnostics.rs
crates/fluvio-cluster/src/cli/shutdown.rs
crates/fluvio-cluster/src/cli/start/local.rs
crates/fluvio-cluster/src/cli/start/mod.rs
crates/fluvio-cluster/src/delete.rs
crates/fluvio-cluster/src/lib.rs
crates/fluvio-cluster/src/start/k8.rs
crates/fluvio-cluster/src/start/local.rs
crates/fluvio-spu/Makefile
crates/fluvio-test-util/setup/environment/local.rs
crates/fluvio/src/config/config.rs
tests/cli/fluvio_read_only/basic.bats
tls/Makefile

Installation type (Local, LocalK8, K8, ReadOnly) will be stored in the profile after `fluvio cluster start --local/k8/local-k8/read-only` and will be used in other cluster operations, so, the user does need to specify it on `fluvio cluster delete/shutdown/diagnostics`

 feat: use installation type in cli commands

---

crates/fluvio-version-manager/src/command/list.rs
crates/fluvio-version-manager/src/command/mod.rs
crates/fluvio-version-manager/src/command/switch.rs
crates/fluvio-version-manager/src/main.rs
tests/cli/fvm_smoke_tests/fvm_basic.bats

These are a couple of very small changes in FVM to make the UI more intuitive.
<div align=center>
<br />
<small>Using switch on Channels now prints the underlying tag</small>
</div>
<div align=center>
<br />
<small>Now `fvm list` is used to list versions</small>
</div>

feat: fvm user interface improvements

---

.github/workflows/publish.yml
actions/publish-pkgset.sh
makefiles/release.mk

Publishes PackageSets as part of bumping Fluvio version.

feat: publish PackageSet on Fluvio Publish

---

makefiles/release.mk

Fallback to `true` in case the process of publishing a Package fails, this allows us to
bypass existing package re-publish error which aborts the publish process.

fix: skip already published instead of aborting

---

.github/workflows/publish.yml
.github/workflows/release.yml

Add `BPKG_TOKEN` environment variable for `bump-fluvio-stable` and `bump-fluvio-latest`.

fix: map `BPKG_TOKEN` for `bump_fluvio` job

---

.github/workflows/ci.yml
.github/workflows/publish.yml

while ci merge is still occuring on failed CI, go back to repo dispatch that only publishs on successful done step

chore: ci, perms for publish trigger on repo_dispatch to cd_dev

---

crates/fluvio-stream-dispatcher/src/metadata/k8.rs
crates/fluvio-stream-model/src/store/k8.rs

There were two places where `owner_references` were lost after conversions:
1. From `ObjectMeta` to `K8MetaItem` if `resource_version` is empty.
2. `InputObjectMeta` = `ObjectMeta::into()` does not pass `owner_references`, instead need to use `ObjectMeta::as_input()`

fix: properly pass owner references in conversions

---

crates/fluvio/src/config/cluster.rs
crates/fluvio/src/config/config.rs
crates/fluvio/test-data/profiles/config.toml
crates/fluvio/test-data/profiles/updatable_config.toml

We have a problem when a test fails intermittently to read the config file.
Most tests only read the config file, but one is also modifying it, so I changed it so that the test has its own config file.
I'm not entirely sure that this solves the issue. I've run the CI a couple of times after the changes, and it didn't fail once, but that could be just luck.
fixes: #3707

fix: use a different file for tests updating the config

---

crates/fluvio-hub-util/src/package.rs
crates/fluvio-version-manager/src/common/version_installer.rs
rust-toolchain.toml

A new Rust version just dropped
https://blog.rust-lang.org/2023/11/16/Rust-1.74.0.html

chore: upgrade to Rust 1.74.0

---

crates/fluvio-hub-util/src/package.rs
crates/fluvio-version-manager/src/common/version_installer.rs
rust-toolchain.toml

clippy updates from @matheus-consoli! Provided on #3713.
---
This used to turn off FVM tests and also includes fixes on Rust update by @matheus-consoli but given that PackageSet is now fixed by hotpatch (kudos to @digikata), this only includes @matheus-consoli update!

chore: updates Rust 1.74 (#3713)

---

tests/cli/fvm_smoke_tests/fvm_basic.bats

Mixing artifact state w/ dev-hub status instead of hub objects was causing failures.

ci: fvm_basic.bats, smoke test adjustment

---

.github/workflows/cd_dev.yaml
.github/workflows/ci.yml
.github/workflows/hourly.yml
Cargo.lock
crates/fluvio-cli/Cargo.toml
crates/fluvio-cli/src/profile/add.rs
crates/fluvio-cli/src/profile/list.rs
crates/fluvio-cluster/Cargo.toml
crates/fluvio-cluster/src/check/mod.rs
crates/fluvio-cluster/src/cli/delete.rs
crates/fluvio-cluster/src/cli/diagnostics.rs
crates/fluvio-cluster/src/cli/shutdown.rs
crates/fluvio-cluster/src/cli/start/local.rs
crates/fluvio-cluster/src/cli/start/mod.rs
crates/fluvio-cluster/src/delete.rs
crates/fluvio-cluster/src/lib.rs
crates/fluvio-cluster/src/start/k8.rs
crates/fluvio-cluster/src/start/local.rs
crates/fluvio-extension-common/Cargo.toml
crates/fluvio-extension-common/src/installation.rs
crates/fluvio-extension-common/src/lib.rs
crates/fluvio-spu/Makefile
crates/fluvio-test-util/setup/environment/local.rs
crates/fluvio/Cargo.toml
crates/fluvio/src/config/config.rs
tests/cli/fluvio_read_only/basic.bats
tls/Makefile

This is the second attempt of https://github.com/infinyon/fluvio/pull/3675 and https://github.com/infinyon/fluvio/pull/3681 with the only difference that `InstallationType` is put to `fluvio-extension-common` crate due `fluvio-cluster` crate is not always available for `fluvio-cli`, and in general, it occurred to me that this is a more appropriate place.

feat: use installation type in cli commands

---

Cargo.lock
crates/fluvio-protocol-derive/Cargo.toml
crates/fluvio-protocol-derive/src/ast/container.rs
crates/fluvio-protocol-derive/src/ast/enum.rs
crates/fluvio-protocol-derive/src/ast/prop.rs
crates/fluvio-protocol-derive/src/util.rs
crates/fluvio-spu-schema/Cargo.toml
crates/fluvio-spu-schema/src/produce/request.rs

Hello, I took on updating the  `fluvio-protocol-derive` from `syn1` to `syn2` from #3577
I checked all the tests and of course are passing, but there is something I am not sure about.
Here it is expecting `Literal` value
https://github.com/infinyon/fluvio/blob/d0dd8595583c0dd4651713beb637fb0b5c48c7fb/crates/fluvio-protocol-derive/src/ast/prop.rs#L200C29-L200C29
but there is one place in the code in the `fluvio-spu-schema` crate, that `PRODUCER_TRANSFORMATION_API` is being passed as a value. Because this is not a `Literal` but a `Path` it actually never goes inside the if statement.  Also not sure but I couldn't find this constant anywhere. 
https://github.com/infinyon/fluvio/blob/d0dd8595583c0dd4651713beb637fb0b5c48c7fb/crates/fluvio-spu-schema/src/produce/request.rs#L44C16-L44C16
So …

Updating fluvio-protocol-derive crate from syn1 to syn2

---

crates/fluvio-hub-util/src/fvm/api/client.rs
tests/cli/fvm_smoke_tests/fvm_basic.bats

Update Hub FVM API Client to bubble up `ApiError` responses as messages.
<div align=center>
<br />
<small>Message errors from API are now rendered</small>
</div>
<div align=center>
<br />
<small>Using `RUST_LOG=debug` messages from API will be shown</small>
</div>

fix: render errors from Hub API accordingly

---

Cargo.lock
crates/fluvio-cli-common/Cargo.toml
crates/fluvio-cli-common/src/lib.rs
crates/fluvio-cli-common/src/smartmodule.rs
crates/fluvio-cli/Cargo.toml
crates/fluvio-cli/src/client/smartmodule/mod.rs
crates/fluvio-cli/src/client/smartmodule/test.rs
crates/smartmodule-development-kit/Cargo.toml
crates/smartmodule-development-kit/src/test.rs
tests/cli/fluvio_smoke_tests/smartmodule-basic.bats

Closes #3553
Moves most of the `TestCdm` from the smdk to `fluvio-cli-common` and reutilizes it from `fluvio-cli` and `smartmodule-development-kit`.
The API for `smdk` is unchanged.
The API for `fluvio sm test` is mostly the same, except for removing:
```sh
--release <RELEASE>                  Release profile name [default: release-lto]
-p, --package-name <PACKAGE_NAME>        Optional package/project name
--wasm-file <WASM_FILE>              Optional wasm file path
```
Download a SM from the hub:
```sh
fluvio hub download infinyon/regex-filter@0.1.0
```
and run a test for it:
```sh
fluvio sm test -t '{"uses":"infinyon/regex-filter@0.1.0", "with": {"regex": "^fl"}}' --text 'fluvio' 
```

chore: clone `smdk test` to `fluvio sm test`

---

Cargo.lock
crates/fluvio-version-manager/Cargo.toml
crates/fluvio-version-manager/src/command/itself/mod.rs
crates/fluvio-version-manager/src/command/itself/update.rs

- Hide `fvm self install` as its only used for install script
- Provide update details via `fvm self update`
- Bumps patch version number to `0.1.1`

feat: hide `fvm self install` from and help introduce `fvm self update`

---

tests/cli/cdk_smoke_tests/cdk-basic.bats
tests/cli/cdk_smoke_tests/cdk-multi-partition-consumer.bats
tests/cli/cli-platform-cross-version.bats
tests/cli/fluvio_smoke_tests/non-concurrent/cluster-delete.bats
tests/cli/fvm_smoke_tests/fvm_basic.bats
tests/cli/smdk_smoke_tests/smdk-basic.bats
tests/cli/test_helper/tools_check.bash

Currently, unless explicitly disabled, it tries to run Fluvio cluster on every run of bats test file. It is often forgotten which led to wasting a lot of time in CI.

chore: remove implicit cluster start from tests

---

.github/workflows/cd_dev.yaml
.github/workflows/cd_dev_mac.yaml
.github/workflows/hourly.yml
tests/cli/cli-platform-cross-version.bats
tests/upgrade-test.sh

1. `CD_DEV` and `CD_DEV_Mac` - do not install k8s for local clusters, explicitly set installation type so it won't be broken when defaults change.
2. `Hourly` - added local cluster to longevity tests, set it to every 2 hours instead of every hour to compensate for increased CI time.

chore: update local clusters setup on CD and Hourly

---

.github/workflows/ci.yml
crates/fluvio-cluster/src/cli/check.rs
crates/fluvio-cluster/src/cli/delete.rs
crates/fluvio-cluster/src/cli/diagnostics.rs
crates/fluvio-cluster/src/cli/mod.rs
crates/fluvio-cluster/src/cli/shutdown.rs
crates/fluvio-cluster/src/cli/start/mod.rs
crates/fluvio-cluster/src/cli/status.rs
crates/fluvio-cluster/src/cli/upgrade.rs
crates/fluvio-cluster/src/start/k8.rs
crates/fluvio-cluster/src/start/local.rs

Cluster operations `upgrade`, `check`, and `status` should be aware of the installation type of the cluster.
Additionally, setting the profile during the installation is put before any actual actions to the system, so in case of failure, the delete command will clean up accordingly.

feat: support cluster upgrade/check/status for local cluster

---

.github/workflows/cd_release.yml
.github/workflows/ci.yml
.github/workflows/ci_mac.yaml
actions/action-install-fluvio-cluster.sh
k8-util/cluster/kind.sh
makefiles/test.mk
tests/longevity-producer.sh
tls/Makefile

Set explicitly `k8` cluster type where it is required. This is preparation for changing local cluster type as default on cluster start.

chore: explicitly set cluster type in CI/CD

---

crates/fluvio-cluster/src/cli/start/local.rs
crates/fluvio-cluster/src/cli/start/mod.rs
crates/fluvio-cluster/src/cli/upgrade.rs

Set the `local` cluster as a default one for `fluvio cluster start`.
Closes infinyon/roadmap#160

feat: make local cluster as default in cli

---

Cargo.lock
crates/fluvio-version-manager/Cargo.toml
crates/fluvio-version-manager/src/command/mod.rs
crates/fluvio-version-manager/src/command/uninstall.rs
crates/fluvio-version-manager/src/command/version.rs
crates/fluvio-version-manager/src/common/version_directory.rs
crates/fluvio-version-manager/src/main.rs
tests/cli/fvm_smoke_tests/fvm_basic.bats

Introduces a `fvm uninstall` command to clean up `~/.fvm/versions` directory by allowing
the user to uninstall specific versions.
Also updates logic to use Fluvio version for Version Output.
https://github.com/infinyon/fluvio/assets/34756077/6c9e58a1-6515-4b28-aff5-ce51e6b23e72

feat: fvm uninstall command

---

Cargo.lock
crates/fluvio-cluster/src/cli/check.rs
crates/fluvio-cluster/src/cli/delete.rs
crates/fluvio-cluster/src/cli/diagnostics.rs
crates/fluvio-cluster/src/cli/start/mod.rs
crates/fluvio-cluster/src/cli/upgrade.rs
crates/fluvio-cluster/src/start/local.rs
crates/fluvio-extension-common/Cargo.toml
crates/fluvio-extension-common/src/installation.rs

Added new installation type `Docker` with minimal support: it is only possible to add it manually and it won't allow to do commands that do not support it. It prevents errors if fluvio cli runs against clusters in docker.

feat: added minimal support for docker inst type

---

.github/actions/setup-fluvio/action.yml

Setups a GitHub Action to install Fluvio using the installation script and FVM.
```diff
-     - name: Install stable CLI and start Fluvio cluster
-        run: |
-          curl -fsS https://hub.infinyon.cloud/install/install.sh?ctx=ci | bash
-          echo "~/.fluvio/bin" >> $GITHUB_PATH
+      - name: Setup Fluvio
+        uses: infinyon/fluvio/.github/actions/setup-fluvio
```
> Open Question: Perhaps we can also host the action file on root dir, which would result in a slightly change from: `infinyon/fluvio/.github/actions/setup-fluvio`  to: `infinyon/fluvio/actions/setup-fluvio`
The following is an example from tho repository fork, where the option `version` is supported and defaults to `stable`.
Refer to workflow run here: https://github.com/infinyon/fluvio/actions/runs/7185354341/jo …

feat: setup fluvio gh action

---

.github/workflows/cd_dev.yaml
.github/workflows/cd_dev_mac.yaml
.github/workflows/cd_release.yml
.github/workflows/ci.yml
.github/workflows/connector-publish.yml
.github/workflows/hourly.yml
.github/workflows/smartmodule-publish.yml

Uses `setup-fluvio` instead of in-situ cURL call to install Fluvio.

chore: use `setup-fluvio` action

---

crates/fluvio-cluster/src/start/local.rs

Using IP instead of `localhost` for local clusters saves us from extra table lookup and, prevents issues when there is no `localhost` entry in hosts file. 
Fixes #3783

feat: use ip in local profile

---

crates/fluvio-cli-common/src/smartmodule.rs
crates/fluvio-cli/src/client/consume/mod.rs
crates/fluvio-cli/src/client/produce/mod.rs
smartmodule/examples/aggregate-init/README.md
smartmodule/examples/filter_hashset/README.md
smartmodule/examples/filter_look_back/README.md
smartmodule/examples/filter_look_back_with_timestamps/README.md

In the following commands: `smdk test`, `fluvio sm test`, `fluvio produce`, `fluvio consume`
Argument `--transform` renamed to `--transforms_line` and `--transforms_file` to `--transforms` with short version `-t`.
Old names will also be supported (but hidden from help) for at least one version to support current CLI tests for cross-version combinations. 
Fixes #3773

feat:rename `transform` and `transforms-file` args

---

.github/workflows/ci.yml
crates/fluvio-version-manager/src/command/install.rs
crates/fluvio-version-manager/src/command/update.rs
tests/cli/fvm_smoke_tests/fvm_basic.bats

Uses `INFINYON_HUB_REMOTE` over `HUB_REGISTRY_URL` to follow other solutions convention.

fix: use `INFINYON_HUB_REMOTE`  over `HUB_REGISTRY_URL` for FVM

---

crates/fluvio-cli-common/src/version_cmd/mod.rs

Exports functions to get current OS, calculate SHA256 for current executable and detect
current platform.

chore: export utility functions from version printing

---

Cargo.lock
crates/cdk/Cargo.toml
crates/fluvio-cli-common/Cargo.toml
crates/fluvio-cli-common/src/version_cmd/basic.rs
crates/fluvio-cli-common/src/version_cmd/mod.rs

Provides an optional `--json` parameter to the `BasicVersionCmd` to have `version` details
printed in JSON. This is useful when used along with `jq` on CI/CD/Automation.
This capability is used behind a _feature flag_ that uses `serde` and `serde_json` so
its not automatically added and can be skipped if not needed in some scenarios.
```
Desktop cdk version
CDK        : 0.11.3-dev-1
CDK Arch   : aarch64-apple-darwin
CDK SHA256 : 180a8184267524a3797675470d1e6e94a0607979b6cd36e580e2d842aba6a51a
OS Details : Darwin 13.5.2 (kernel 22.6.0)
➜  Desktop cdk version --json
{
"name": "CDK",
"version": "0.11.3-dev-1",
"OS Details": "Darwin 13.5.2 (kernel 22.6.0)",
"CDK Arch": "aarch64-apple-darwin",
"CDK SHA256": "180a8184267524a3797675470d1e6e94a0607979b6cd36e580e2d842aba6a51a"
}
➜  Desktop cdk …
```

feat: `FluvioVersionPrinter` support for json output

---

makefiles/release.mk

This needs to be patched into CI for fluvio-packages until the next stable release completes (because stable is used for fluvio-packages d/l).
In theory this should fix the hourly test failures

chore: ci publish patch

---

.github/workflows/release.yml

update fluvio stable release flow to also generate a docker stable tag

chore: ci, tag stable fluvio releases with stable in docker hub

---

crates/fluvio-version-manager/tests/install-fvm.sh

I installed fluvio on my two machines this weekend with: 
```bash
curl -fsS https://hub.infinyon.cloud/install/install.sh | bash
```
Worked well on my MacBook, but the installation crashed on my Debian which didn't have `unzip` command installed. 
I am not sure if this is the correct installation bash script.

chore: exit when there is no unzip cmd

---

crates/fluvio-hub-util/src/fvm/mod.rs
crates/fluvio-version-manager/src/command/current.rs
crates/fluvio-version-manager/src/command/update.rs
crates/fluvio-version-manager/src/common/settings.rs
crates/fluvio-version-manager/src/common/version_directory.rs

support latest ssdk release label

fix: fvm should allow general pkgset labels

---

.github/workflows/publish.yml

final bump was bumping previous sha

chore: ci publish, fix misaligned sha

---

Cargo.lock
crates/fluvio/Cargo.toml
crates/fluvio/src/consumer.rs

Derive Clone require type parameter be bound by `Clone` too, here `P` in `Arc<P>`, so refactor it by manually.

Manually impl Clone for PartitionConsumer.

---

crates/fluvio-version-manager/src/command/list.rs
crates/fluvio-version-manager/src/common/manifest.rs
crates/fluvio-version-manager/src/common/settings.rs
crates/fluvio-version-manager/src/common/version_installer.rs
tests/cli/fvm_smoke_tests/fvm_basic.bats

Introduces support to list versions of artifacts used in a FVM channel/version.
Given that currently FVM doesn't keeps track of installed artifacts, for previous versions
users are prompted to reinstall the version in order to update this data.
https://github.com/infinyon/fluvio/assets/34756077/242a1bf3-d99c-42a0-aadf-2e8582c76456
**Listing artifacts headers**

feat(fvm): list included artifacts with `fvm list <channel>`

---

Cargo.lock
crates/fluvio-cli/src/profile/list.rs
crates/fluvio-cluster/src/cli/check.rs
crates/fluvio-cluster/src/cli/delete.rs
crates/fluvio-cluster/src/cli/diagnostics.rs
crates/fluvio-cluster/src/cli/mod.rs
crates/fluvio-cluster/src/cli/shutdown.rs
crates/fluvio-cluster/src/cli/start/mod.rs
crates/fluvio-cluster/src/cli/status.rs
crates/fluvio-cluster/src/cli/upgrade.rs
crates/fluvio-extension-common/Cargo.toml
crates/fluvio-extension-common/src/installation.rs
crates/fluvio/Cargo.toml
crates/fluvio/src/config/cluster.rs

Limit confusing crossovers of fluvio local clusters  w/ fluvio cloud clusters
`fluvio profile list` will also correctly identify Cloud cluster
profiles

fix: limit fluvio cluster cmds from operating on a fluvio cloud cluster

---

crates/fluvio-spu/src/services/public/produce_handler.rs
crates/fluvio-storage/src/error.rs
crates/fluvio-storage/src/replica.rs

If the batch size exceeds the max segment size, the storage never will be able to store the data.
Added a check to validate and prevent this situation before writing to the segment. 
Fixes #3891

fix: check if batch size exceeds segment size

---

Cargo.lock
Cargo.toml
crates/fluvio-kv-storage/Cargo.toml
crates/fluvio-kv-storage/src/lib.rs
crates/fluvio-kv-storage/src/log.rs

Added `fluvio-kv-storage` crate that contains traits and types for general KV storage and log-based storage impl. The `Log` type and traits are also defined there.

feat: added fluvio kv storage crate

---

Cargo.lock
Cargo.toml
crates/fluvio-cli/Cargo.toml
crates/fluvio-cli/src/bin/main.rs
crates/fluvio-sc/Cargo.toml
crates/fluvio-sc/src/bin/main.rs
crates/fluvio-spu/Cargo.toml
crates/fluvio-spu/src/main.rs

Switch to [mimalloc](https://crates.io/crates/mimalloc) to improve performance.
Only add to main to reduce allocator conflict in library

perfor: switch to high perform allocator

---

connector/json-test-connector/sample-config2-v2.yaml
crates/cdk/Cargo.toml
crates/cdk/src/deploy.rs
crates/cdk/src/test.rs
crates/fluvio-connector-deployer/src/lib.rs
tests/cli/cdk_smoke_tests/cdk-basic.bats
tests/cli/cdk_smoke_tests/cdk-multi-deploy.bats
tests/cli/cdk_smoke_tests/cdk-multi-partition-consumer.bats

- **chore: sort Cargo.toml dep section**
- **fix: cdk deploy, fix contention on ipkg binary and/or log path**
- **add cdk multi connector coverage tests**
- **cdk: cleanup ipkg tmp files on 'deploy shutdown**
fixes #3903

fix: cdk deploy, fix contention on ipkg binary and/or log path

---

Cargo.lock
Cargo.toml
crates/fluvio-cli/src/client/partition/list.rs
crates/fluvio-cli/src/client/topic/list.rs
crates/fluvio-controlplane-metadata/Cargo.toml
crates/fluvio-controlplane-metadata/src/partition/spec.rs
crates/fluvio-controlplane-metadata/src/topic/spec.rs
crates/fluvio-sc-schema/Cargo.toml
crates/fluvio-sc-schema/src/objects/list.rs
crates/fluvio-sc-schema/src/objects/mod.rs
crates/fluvio-sc/src/services/public_api/list.rs
crates/fluvio-sc/src/services/public_api/partition/mod.rs
crates/fluvio-sc/src/services/public_api/topic/fetch.rs
crates/fluvio/src/admin.rs
crates/fluvio/src/consumer/mod.rs
k8-util/helm/fluvio-sys/templates/crd_partition.yaml
k8-util/helm/fluvio-sys/templates/crd_topic.yaml

Added an ability to create hidden topics, which by default will not be shown on cli.
To see them, need to use `--system` cli arg. This is needed for "special" offsets topic.

feat: added hidden topics and partitions

---

Cargo.lock
crates/fluvio-cluster/src/cli/mod.rs
crates/fluvio-cluster/src/cli/resume.rs
crates/fluvio-cluster/src/delete.rs
crates/fluvio-cluster/src/lib.rs
crates/fluvio-cluster/src/start/local.rs
crates/fluvio-types/Cargo.toml
crates/fluvio-types/src/config_file.rs
crates/fluvio-types/src/lib.rs
crates/fluvio/src/config/cluster.rs
crates/fluvio/src/config/config.rs
makefiles/test.mk
smartmodule/examples/Cargo.lock
tests/cli/fluvio_smoke_tests/local-resume.bats
tests/cli/fluvio_smoke_tests/non-concurrent/local-resume.bats

This is a draft first change for [issue 3810](https://github.com/infinyon/fluvio/issues/3810)
If we agree that we need to store the local cluster configuration in a file - this commit is the first step before adding more edge cases and error handling

Scaffold resume - local config persisted between runs

---

crates/fluvio-cli/src/client/topic/delete.rs
crates/fluvio-protocol/src/link/error_code.rs
crates/fluvio-sc-schema/src/objects/delete.rs
crates/fluvio-sc/src/services/public_api/delete.rs
crates/fluvio-sc/src/services/public_api/topic/delete.rs
crates/fluvio/src/admin.rs
tests/cli/fluvio_smoke_tests/system-topic-basic.bats

If user tries to delete a system topic:
```bash
$ fluvio topic delete consumer-offset
system topic 'consumer-offset' can only be deleted forcibly
```
with the `--system` argument:
```bash
$ fluvio topic delete consumer-offset --system
You are trying to delete a system topic 'consumer-offset'. It can affect the functioning of the cluster.
Are you sure you want to proceed? (y/n)
y
system topic "consumer-offset" deleted
```
with `--system` and `--force`:
```bash
$ fluvio topic delete consumer-offset --system --force
system topic "consumer-offset" deleted
```

feat: disallow deletion system topic unless forced

---

crates/fluvio-cli/src/client/consume/mod.rs
crates/fluvio-test/src/tests/consumer_offsets/mod.rs
crates/fluvio/src/consumer/config.rs
crates/fluvio/src/fluvio.rs
tests/cli/fluvio_smoke_tests/e2e-basic.bats

Added support for a list of partitions instead of just "one" or "all". This is supported in the old API, and we would want to keep it.
Reverted one CLI test that was previously changed.

feat: support subset of partitions in consumer ext

---

crates/fluvio-benchmark/src/consumer_worker.rs
crates/fluvio-connector-common/src/consumer.rs
crates/fluvio-test-util/test_runner/test_driver/mod.rs
crates/fluvio-test/src/tests/batching/mod.rs
crates/fluvio-test/src/tests/concurrent/consumer.rs
crates/fluvio-test/src/tests/consumer.rs
crates/fluvio-test/src/tests/data_generator/mod.rs
crates/fluvio-test/src/tests/data_generator/producer.rs
crates/fluvio-test/src/tests/election/mod.rs
crates/fluvio-test/src/tests/longevity/consumer.rs
crates/fluvio-test/src/tests/multiple_partitions/consumer.rs
crates/fluvio-test/src/tests/reconnection/mod.rs
crates/fluvio-test/src/tests/smoke/consume.rs
crates/fluvio/src/consumer/config.rs
crates/fluvio/src/consumer/mod.rs
crates/fluvio/src/fluvio.rs
crates/fluvio/src/lib.rs
examples/02-consume/src/main.rs
examples/03-echo/src/main.rs

Set the old consumer API as deprecated and replace its usages with the new one.
Fixes infinyon/roadmap#234

feat: set old consumer API deprecated

---

crates/fluvio-connector-common/src/consumer.rs
crates/fluvio-connector-package/src/config/mod.rs
crates/fluvio-connector-package/test-data/connectors/full-config-v2.yaml
tests/cli/cdk_smoke_tests/cdk-multi-partition-consumer.bats

Added support of consumer offsets to connectors config.
Config example:
```yaml
consumer:
partition: 10
max_bytes: "1 MB"
id: "consumer_id_1"
offset:
start:
absolute: 100
strategy: auto
flush-period:
secs: 160
nanos: 0
```

feat: added consumer offset to connector config

---

Cargo.lock
connector/sink-test-connector/sample-config-v2.yaml
connector/sink-test-connector/sample-config.yaml
connector/sink-test-connector/src/main.rs
crates/fluvio-connector-common/src/consumer.rs
crates/fluvio/Cargo.toml
crates/fluvio/src/consumer/stream.rs
tests/cli/cdk_smoke_tests/cdk-multi-partition-consumer.bats

Use the `ConsumerStream` trait with offset management capabilities in the common connectors dependencies.

feat: use `ConsumerStream` trait in connectors

---

Cargo.lock
crates/fluvio-cli/Cargo.toml
crates/fluvio-cli/src/client/consume/mod.rs

Added graceful shutdown for the `consume` CLI operation.
Fixes #3963

feat(cli): graceful period for stream interruption

---

Cargo.lock
crates/fluvio-cli/src/client/topic/create.rs
crates/fluvio-controlplane-metadata/src/lib.rs
crates/fluvio-controlplane-metadata/src/mirroring/mod.rs
crates/fluvio-sc-schema/src/apis.rs
crates/fluvio-sc-schema/src/lib.rs
crates/fluvio-sc-schema/src/mirroring/mod.rs
crates/fluvio-sc-schema/src/request.rs
crates/fluvio-sc/Cargo.toml
crates/fluvio-sc/src/controllers/mirroring/controller.rs
crates/fluvio-sc/src/controllers/mirroring/mod.rs
crates/fluvio-sc/src/controllers/mod.rs
crates/fluvio-sc/src/init.rs
crates/fluvio-sc/src/services/public_api/api_version.rs
crates/fluvio-sc/src/services/public_api/mirroring/connect.rs
crates/fluvio-sc/src/services/public_api/mirroring/mod.rs
crates/fluvio-sc/src/services/public_api/mod.rs
crates/fluvio-sc/src/services/public_api/public_server.rs
crates/fluvio-sc/src/services/public_api/topic/create.rs
crates/fluvio-socket/Cargo.toml
crates/fluvio-socket/src/lib.rs
crates/fluvio-socket/src/stream_socket.rs
crates/fluvio-spu/src/core/leader_client.rs
crates/fluvio/src/lib.rs
crates/fluvio/src/spu.rs

Needs: 
What is changed:
What is missing for futures pull requests:
- update topic commands: `--mirror-add`, `--mirror-delete`, `--mirror-apply`
- handling TLS
- delete topic on remote when delete it on home
- spu-to-spu connection
On home side:
```bash
$ flvd cluster start --k8 --develop
$ flvd remote register remote1
$ echo '[                                                                                                                                                                                                               
"remote1"
]' > remote_devices.json 
$ flvd topic create mirror-topic --mirror-apply remote_devices.json
$ flvd remote export remote1 --file remote1.json
```
On remote side:
```bash
$ flvd cluster start --local --develop
$ flvd home connect --file remote1.json …
```

feat: sc-to-sc mirroring connection

---

Cargo.lock
crates/cargo-builder/src/package.rs
crates/fluvio-smartengine/Cargo.toml
crates/fluvio-smartengine/src/engine/wasmtime/engine.rs
crates/smartmodule-development-kit/Cargo.toml
crates/smartmodule-development-kit/src/build.rs
crates/smartmodule-development-kit/src/load.rs
crates/smartmodule-development-kit/src/main.rs
crates/smartmodule-development-kit/src/publish.rs
crates/smartmodule-development-kit/src/test.rs

smkd build/test/load accepts --wasi flags, or set
export SMDK_WASI=true
build build/test/load

smdk(wasi): add build flags for println/panic enabled

---

crates/fluvio-hub-util/src/fvm/mod.rs

Introduces a `PackageSet` method to check for artifacts updates.
This allows to deliver Fluvio tools updates/patches under the same Fluvio version without
having to update the whole PackageSet.

feat(hub): `PackageSet::check_artifact_updates` method

---

crates/fluvio-storage/Cargo.toml

turns out that `fluvio-compression` was hidden dependency to `fluvio-storage`.  This make it explicit, so there is no surprise when used by dependents

chore: add fluvio-compression as required dep

---

Cargo.lock
crates/fluvio-auth/src/x509/authenticator.rs
crates/fluvio-cli/Cargo.toml
crates/fluvio-cli/src/client/remote/export.rs
crates/fluvio-controlplane-metadata/Cargo.toml
crates/fluvio-controlplane-metadata/src/mirror/spec.rs
crates/fluvio-spu/src/mirroring/test/fixture.rs
k8-util/helm/fluvio-sys/Chart.yaml
k8-util/helm/fluvio-sys/templates/crd_mirror.yaml
tests/cli/mirroring_smoke_tests/export.bats

Example: 
```
fluvio remote register user1 
fluvio remote export user1 --file user1.json --key ~/workspace/infinyon/fluvio/tls/certs/client-user1.key --cert ~/workspace/infinyon/fluvio/tls/certs/client-user1.crt
```

feat: export mirror file with tls

---

Cargo.lock
crates/fluvio-auth/src/policy.rs
crates/fluvio-sc/Cargo.toml
crates/fluvio-sc/src/controllers/mirroring/controller.rs
crates/fluvio-sc/src/services/auth/basic.rs
crates/fluvio-sc/src/services/public_api/mirroring/connect.rs
crates/fluvio-sc/src/services/public_api/mirroring/mod.rs
crates/fluvio-sc/src/services/public_api/public_server.rs

feat: tls and authorization on SC mirroring

---

Cargo.lock

Updating time to 0.3.36 to fix this CI on nightly:
https://github.com/infinyon/fluvio/actions/runs/9197478966/job/25298024100
More about:
https://github.com/rust-lang/rust/issues/125319#issuecomment-2120809372

chore: update time to 0.3.36

---

crates/fluvio-cluster/src/cli/start/local.rs
crates/fluvio-cluster/src/cli/start/mod.rs
crates/fluvio-cluster/src/runtime/local/sc.rs
crates/fluvio-cluster/src/start/local.rs

This PR allows runs two local clusters in the same environment.
Added in this PR: 
- Option to change data_dir
- Option to change public and private SC addresses
- Option --skip-profile-creation for local cluster, now allows creating a profile manually before.
```bash
flvd cluster start
flvd profile add user1 127.0.0.1:9103 local 
flvd cluster start --skip-profile-creation --skip-checks --spu 0 --sc-pub-addr 127.0.0.1:9103 --sc-priv-addr 0.0.0.0:9104 --data-dir ~/.fluvio_2 
flvd cluster spu register --id 6001 -p 0.0.0.0:9020 -v 0.0.0.0:9021
flvd run spu -i 6001 -p 0.0.0.0:9020 -v 0.0.0.0:9021 --sc-addr localhost:9104 --log-base-dir ~/.fluvio_2/data 
```
The actual implementation for deleting a cluster on local mode is deleting all executables with `fluvio` as name. I propose creating an …

feat: add sc opts to cluster start

---

crates/fluvio-version-manager/Cargo.toml
crates/fluvio-version-manager/src/command/itself/install.rs
crates/fluvio-version-manager/src/command/itself/update.rs
crates/fluvio-version-manager/src/common/executable.rs
crates/fluvio-version-manager/src/common/mod.rs
crates/fluvio-version-manager/src/common/notify.rs
crates/fluvio-version-manager/src/common/update_manager.rs
crates/fluvio-version-manager/src/common/version_installer.rs
tests/cli/fvm_smoke_tests/fvm_basic.bats

Provides support to update FVM with `fvm self update`.
Current behavior doesn't check for "greater" versions, but instead just checks if versions
are different. By default `stable` fvm channel is checked.
In order to overwrite the version to update of FVM an environment variable
`FVM_UPDATE_VERSION` can be used to provide the tag to be used at the moment of fetching
the FVM version.
https://github.com/infinyon/fluvio/assets/34756077/bcc6f226-5ee3-433e-922a-95dc9778d371

feat(fvm): `fvm self update` support

---

crates/smartmodule-development-kit/src/publish.rs
tests/cli/smdk_smoke_tests/smdk-basic.bats

Ensures the README is included as part of the package tarball on publish with `smdk publish`

feat(smdk): publish support for readme

---

Cargo.lock
Cargo.toml
crates/fluvio-cli/Cargo.toml
crates/fluvio-cli/src/client/consume/mod.rs
crates/fluvio-cli/src/client/produce/mod.rs

Uses `std::io::IsTerminal` over `atty` to detect tty environments in Fluvio CLI.

feat(cli): use `std::io::IsTerminal` over `atty`

---

crates/fluvio-cli/src/client/topic/add_partition.rs
tests/cli/fluvio_smoke_tests/add-partitions.bats

I thought that `admin.list` it was filtering the exact string, but it is using "contains" string logic.

Fix add partition not found

---

Cargo.lock
Cargo.toml

Updates `bytes` crate in order to allow newer k8-client versions.

chore: update bytes crate

---

Cargo.lock
crates/fluvio-stream-dispatcher/Cargo.toml
crates/fluvio-stream-dispatcher/src/lib.rs
crates/fluvio-stream-dispatcher/src/metadata/local.rs
crates/fluvio-stream-dispatcher/src/metadata/mod.rs

Needed for: https://github.com/infinyon/fluvio/pull/4090
This PR makes possible to import `LocalMetadataItem` without the `k8` flag

chore: access local metadata without k8 flag

---

crates/fluvio-sc/src/controllers/topics/policy.rs
crates/fluvio-sc/src/stores/topic/store.rs
tests/cli/fluvio_smoke_tests/add-partitions.bats

Solves: https://github.com/infinyon/fluvio/issues/4095

Fix delete topic partitions

---

Cargo.lock
DEVELOPER.md
makefiles/check.mk

While working on building the Fluvio image to run in Kubernetes on macOS I found that
cross-compilation of Fluvio might have some incompatibility issues.
In order to speed up development I ended up using `zigbuild` as an alternative to cross-compile Fluvio.
In the future, perhaps it would be nice to detect host's OS and conditionally use `zigbuild` if running on `macOS` for such step.

chore: default to zigbuild for cross-compilation

---

crates/fluvio-run/src/bin/main.rs

I think that had a refactoring removing not used features flags, but I noticed that it was removed a block of code enabling tracing subscribe when `telemetry` feature was disabled.
I noticed this because only prints were working, all the tracings functions stopped working.
Related: https://github.com/infinyon/fluvio/pull/4118.

fix: enable tracing subscribe again

---

Cargo.lock
Cargo.toml

This version fixed the cross-compilation bug. 
Related:
- https://github.com/bytecodealliance/wasmtime/issues/8898
- https://github.com/bytecodealliance/wasmtime/pull/9100

chore: update wasmtime and wasi-common to 23.0.2

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
crates/fluvio-cli/src/client/home/status.rs
crates/fluvio-cli/src/client/remote/list.rs
crates/fluvio-controlplane-metadata/src/mirror/status.rs
crates/fluvio-controlplane/src/sc_api/api.rs
crates/fluvio-controlplane/src/sc_api/mod.rs
crates/fluvio-controlplane/src/sc_api/update_mirror.rs
crates/fluvio-sc-schema/Cargo.toml
crates/fluvio-sc-schema/src/objects/mod.rs
crates/fluvio-sc/Cargo.toml
crates/fluvio-sc/src/controllers/mirroring/controller.rs
crates/fluvio-sc/src/services/private_api/private_server.rs
crates/fluvio-sc/src/services/public_api/mirroring/connect.rs
crates/fluvio-spu-schema/Cargo.toml
crates/fluvio-spu-schema/src/server/mirror.rs
crates/fluvio-spu/src/control_plane/dispatcher.rs
crates/fluvio-spu/src/control_plane/message_sink.rs
crates/fluvio-spu/src/core/global_context.rs
crates/fluvio-spu/src/kv/consumer.rs
crates/fluvio-spu/src/mirroring/home/connection.rs
crates/fluvio-spu/src/mirroring/remote/controller.rs
crates/fluvio-spu/src/replication/leader/kv.rs
crates/fluvio-spu/src/replication/leader/leaders_state.rs
crates/fluvio-spu/src/replication/leader/replica_state.rs
crates/fluvio/Cargo.toml
tests/cli/mirroring_smoke_tests/e2e/fluvio-core.bats

This PR aims to improve the feedback of the SPU-to-SPU connection on mirroring. Also improving the feedback of the failures showing errors.
- Add two new columns (SPU STATUS and ERRORS) for `fluvio remote list` and `fluvio home status` commands
- Mirror Failed Status Enum now stores an error.
- New private SC API to receive the status from SPU
- A dispatcher on SC to apply these new status
The new error column will show the error from SPU or SC or both. 
When both will be "SC:ERROR SPU:ERROR".
When none will be "-".
Related:
- https://github.com/infinyon/fluvio/issues/4102

feat: update mirror status when find errors on spu

---

.github/workflows/cd_release.yml
.github/workflows/ci.yml
Cargo.lock
crates/fluvio-cluster/Cargo.toml
crates/fluvio-cluster/src/cli/shutdown.rs
crates/fluvio-cluster/src/cli/upgrade.rs
crates/fluvio-cluster/src/start/local.rs
crates/fluvio-controlplane-metadata/src/mirror/status.rs
tests/upgrade-test.sh

Related:
- https://github.com/infinyon/fluvio/issues/962
- https://github.com/infinyon/fluvio/issues/4136
- https://github.com/infinyon/fluvio/issues/4137
Before:
```
▷ flvd cluster upgrade
SPU monitoring socket  /tmp/fluvio-spu.sock, can't be removed: No such file or directory (os error 2)
Uninstalled fluvio local components
📝 Running pre-flight checks
✅ Local Fluvio is not installed
❌ Check Clean Fluvio Local Installation failed Local Fluvio cluster wasn't deleted. Use 'resume' to resume created cluster or 'delete' before starting a new one
💔 Some pre-flight check failed!
Preflight check failed
```
After
```
Upgrade Local Fluvio cluster to version 0.11.12-dev-1? yes
Uninstalled fluvio local components
📝 Checking All Metadatas
✅ Checked All Metadata
🚀 Upgrading Local Fluvio cluster to …
```

feat: upgrade cluster for local

---

crates/fluvio/src/producer/config.rs
crates/fluvio/src/producer/mod.rs

to fix #4099  ,  I did:
1. Create accessor fn for the properties on TopicProducerConfig;
2. Derive Debug;
3. Ignore debug for Box<dyn Partitioner + Send + Sync>;
4. Expose topic and config on TopicProducer;
It is unclear (at least for me :D) if these "non-functional" changes must be unit-tested in some fashion. I am more than happy to implement the needed tests.
Thank you

4099 produce config debug

---

Cargo.lock
crates/cargo-builder/Cargo.toml
crates/cdk/Cargo.toml
crates/fluvio-auth/Cargo.toml
crates/fluvio-cli-common/Cargo.toml
crates/fluvio-cli/Cargo.toml
crates/fluvio-cluster/Cargo.toml
crates/fluvio-controlplane-metadata/Cargo.toml
crates/fluvio-extension-common/Cargo.toml
crates/fluvio-hub-util/Cargo.toml
crates/fluvio-run/Cargo.toml
crates/fluvio-sc-schema/Cargo.toml
crates/fluvio-sc/Cargo.toml
crates/fluvio-service/Cargo.toml
crates/fluvio-smartengine/Cargo.toml
crates/fluvio-socket/Cargo.toml
crates/fluvio-spu/Cargo.toml
crates/fluvio-storage/Cargo.toml
crates/fluvio-stream-dispatcher/Cargo.toml
crates/fluvio-test-derive/Cargo.toml
crates/fluvio-test-util/Cargo.toml
crates/fluvio-test/Cargo.toml
crates/fluvio-version-manager/Cargo.toml
crates/fluvio/Cargo.toml
crates/smartmodule-development-kit/Cargo.toml
release-tools/check-crate-version/toml-diff/Cargo.toml
smartmodule/examples/Cargo.lock
smartmodule/examples/map_json/Cargo.toml
smartmodule/regex-filter/Cargo.lock

Using [cargo-machete](https://github.com/bnjbvr/cargo-machete) I notice some dependencies that we don't use.
I also added a CI step to check them in that PR: https://github.com/infinyon/fluvio/pull/4148/commits

chore: clean up not used dependencies

---

crates/fluvio/src/admin.rs
crates/fluvio/src/fluvio.rs
crates/fluvio/src/lib.rs

Related: https://github.com/infinyon/fluvio/issues/3441

fix: better error when watch api versions are not compatible

---

Cargo.lock
Cargo.toml
crates/fluvio-hub-util/Cargo.toml
crates/fluvio-hub-util/src/fvm/api/download.rs
crates/fluvio-hub-util/src/htclient.rs
crates/fluvio-hub-util/src/hubaccess.rs
crates/fluvio-hub-util/src/lib.rs

Provides `fluvio-hub-util` support for target `wasm32-unknown-unknown`.
Using the feature `wasm` certain `HubAccess` utilities wont be available.

feat(hub): provide `wasm32-unknown-unknown` support for `hub-util`

---

.github/workflows/ci.yml
makefiles/build.mk
tests/upgrade-test.sh

Created an issue to investigate it better: https://github.com/infinyon/fluvio/issues/4162

fix: disable local upgrade test until fix it

---

Cargo.lock
Cargo.toml
crates/cdk/src/deploy.rs
crates/fluvio-cluster/Cargo.toml
crates/fluvio-cluster/src/check/mod.rs
crates/fluvio-cluster/src/cli/diagnostics.rs
crates/fluvio-cluster/src/cli/shutdown.rs
crates/fluvio-cluster/src/delete.rs
crates/fluvio-cluster/src/lib.rs
crates/fluvio-cluster/src/process/mod.rs
crates/fluvio-sc/src/start.rs
crates/fluvio-spu/src/start.rs
crates/fluvio-test/src/main.rs

Update sysinfo to 0.31.4 and fix file descriptor leak on Linux. 
`sysinfo` leaks file descriptors on Linux if the limit is not set.
Spu Before:
```
▷ ls /proc/570230/fd/ | wc -l
1114
```
Spu After:
```
▷ ls /proc/574099/fd/ | wc -l
19
```

fix: update sysinfo and fix fd leak on linux

---

crates/fluvio-cluster/src/cli/delete.rs
crates/fluvio-version-manager/src/command/itself/uninstall.rs
crates/fluvio/src/consumer/mod.rs
rust-toolchain.toml

Updates Rust to version `1.81`.

chore: update Rust `1.81`

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
crates/fluvio-stream-dispatcher/Cargo.toml
crates/fluvio-stream-dispatcher/src/metadata/local.rs
makefiles/test.mk
tests/upgrade-test.sh

This PR must solve the weird deadlocks happening after resuming local cluster with previous data.
Solves: https://github.com/infinyon/fluvio/issues/4162

fix: concurrency problems at local metadata store

---

crates/fluvio-sc/src/controllers/mirroring/controller.rs
crates/fluvio-spu/src/mirroring/remote/controller.rs
tests/cli/mirroring_smoke_tests/e2e/fluvio-core.bats

That should improve to not sleeping a lot at first seconds trying to connect. 
Also helping our mirroring tests be more reliable.

chore: decrease exponential timeout of mirroring

---

crates/fluvio-version-manager/src/command/install.rs
tests/cli/fvm_smoke_tests/fvm_basic.bats

Provides support to override the target triple used when fetching binaries from package registry.
`fvm install` now accepts the `--target` option which takes a [Rust Target Triple](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-1-with-host-tools) thats used to replace the default target which is host's OS target.
Alternately a user could specify `FVM_BINARY_ARCH_TRIPLE` environment variable, used for the same purpose. This is useful for CI environments.
If the target triple is not available, FVM will notify the user before performing any further tasks.
```bash
fvm install latest --target aarch64-unknown-linux-gnu
Error: PackageSet "latest" is not available for architecture: "aarch64-unknown-linux-gnu"
```

feat(fvm): override installed binaries target

---

rfc/produce-message-size.md

`batch_size` producer config must not reject large records, just send them directly.
Create a new `max_request_size` producer config that must reject large messages.
I am using `max_request_size` because Kafka uses `max.request.size` but we can change it to other config name.
Compression sizes should not be used for these producer configs.
Related: 
- https://github.com/infinyon/fluvio/issues/4161
- https://github.com/infinyon/fluvio/pull/4195

docs: produce message size rfc

---

Cargo.lock
crates/fluvio-sc/src/controllers/topics/policy.rs
crates/fluvio-sc/src/stores/topic/store.rs
crates/fluvio-stream-dispatcher/Cargo.toml
crates/fluvio-stream-dispatcher/src/metadata/local.rs

The fix of https://github.com/infinyon/fluvio/pull/4094 was a wrong fix to have sure that all partitions are childrens of its Topic.
I reverted this PR, and I made the `link_parent` and `unlink_parent` more reliable.
Because they were being called correct, but `link_parent` it was using stale objects.
Now they are getting the parent from the store to have sure to not lose data.
How to test:
```
fluvio topic create data
fluvio topic add-partition data
fluvio topic add-partition data
fluvio topic add-partition data
fluvio topic add-partition data
fluvio topic add-partition data
fluvio topic delete data
fluvio partition list
```
Must output no results.
This should also fix logs like these after each 5min (SC_RECONCILIATION_INTERVAL_SEC):
```bash
sc        | 2024-10-25T21:16:09.364724Z ERROR …
```

fix: link_parent more realible and delete topic partitions

---

Cargo.lock
crates/fluvio-spu-schema/Cargo.toml
crates/fluvio-spu-schema/src/server/api.rs
crates/fluvio-spu/src/mirroring/home/home_api.rs
crates/fluvio-spu/src/mirroring/remote/remote_api.rs
crates/fluvio-spu/src/replication/follower/peer_api.rs
crates/fluvio-spu/src/replication/leader/connection.rs
crates/fluvio-spu/src/replication/leader/peer_api.rs

The enum encoding of API was not needed since each api is encoded directly.  Enum is used only for decoding only

chore: remove unneeded encoding mark for api protocol

---

.github/workflows/ci.yml
crates/fluvio-sc-schema/src/objects/watch.rs
makefiles/test.mk
tests/cli/cli-backward-compatibility.bash
tests/cli/cli-platform-cross-version.bats
tests/cli/test_helper/fluvio_dev.bash

This PR aims to create tests to check backward compatibility since a specific version, for now, v0.11.10.
Also, it was fixed the compatibility with v0.11.11 and v0.11.10.

fix: compatibility issues with old versions

---

Cargo.lock
Cargo.toml
crates/fluvio/Cargo.toml
crates/fluvio/src/producer/error.rs
crates/fluvio/src/producer/memory_batch.rs
rfc/produce-message-size.md
tests/cli/fluvio_smoke_tests/produce-error.bats

Related: https://github.com/infinyon/fluvio/issues/4216

feat: show actual record size when throw maximum request size error

---

.github/workflows/cd_dev.yaml
tests/cli/cli-backward-compatibility.bash
tests/cli/test_helper/fluvio_dev.bash

Related: https://github.com/infinyon/fluvio/pull/4258
On my last Pull Request (https://github.com/infinyon/fluvio/pull/4258) I forgot to solve bin fluvio conflicts in setup_fluvio_cluster.
Also, I updated Bats version to catch the error and I tested directly on pull request this time in another commit:
https://github.com/infinyon/fluvio/actions/runs/11847565015/job/33017495561?pr=4260

chore: solve bin fluvio conflicts in setup_fluvio_cluster

---

Cargo.lock
Cargo.toml
crates/fluvio-socket/Cargo.toml

We need bump fluvio-socket as fluvio-protocol was updated, to release a new version to fix the release of fluvio-sc-schema v0.25.0.
https://github.com/infinyon/fluvio/actions/runs/11849569173/job/33023036556

chore: bump fluvio-socket to 0.15.0

---

README.md

Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Fluvio Guru](https://gurubase.io/g/fluvio) to Gurubase. Fluvio Guru uses the data from this repo and data from the [docs](https://www.fluvio.io) to answer questions by leveraging the LLM.
In this PR, I showcased the "Fluvio Guru", which highlights that Fluvio now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to …

Introducing Fluvio Guru on Gurubase.io

---

crates/cdk/src/generate.rs
crates/fluvio-connector-derive/Cargo.toml
crates/fluvio-hub-util/src/cmd/download.rs
crates/fluvio-hub-util/src/cmd/list.rs

Updates references to `SmartConnector` to be `Connector` instead as referred in our docs.

fix: use `Connector` over `SmartConnector` to match docs

---

Cargo.lock
crates/fluvio-connector-common/Cargo.toml
crates/fluvio-connector-common/src/consumer.rs
crates/fluvio-connector-derive/src/generator.rs
crates/fluvio/src/consumer/stream.rs
tests/cli/cdk_smoke_tests/cdk-graceful-shutdown.bats

When a consumer connector disconnects it is not dropping the offset management, then it was losing some record in the offset storage.
I added a graceful shutdown similar to what we have in `fluvio-cli`.

feat: add graceful shutdown for consume connectors

---

crates/cdk/src/deploy.rs
crates/fluvio-connector-common/Cargo.toml
tests/cli/cdk_smoke_tests/cdk-graceful-shutdown.bats

We're shutdown connectors with signal kill that couldn't be handled by the application.
I propose using `SIGTERM` that allows `ctrlc` package to handle with the graceful shutdown.
References:
- https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html

fix: shutdown of the cdk consumer

---

Cargo.lock
connector/sink-test-connector/src/main.rs
crates/fluvio-connector-common/Cargo.toml
crates/fluvio-connector-common/src/lib.rs
crates/fluvio-connector-common/ui-test/ui/config_use_reserved_name_fluvio.stderr
crates/fluvio-connector-common/ui-test/ui/config_use_reserved_name_transforms.stderr
crates/fluvio-connector-common/ui-test/ui/struct_without_config.stderr
crates/fluvio-connector-derive/src/generator.rs
crates/fluvio/src/consumer/offset.rs
crates/fluvio/src/consumer/stream.rs
tests/cli/cdk_smoke_tests/cdk-graceful-shutdown.bats

Related: https://github.com/infinyon/fluvio/pull/4273
This PR fixes an issue where streams could fail to drop in certain states, leading to resource leaks. The solution ensures the future managing the stream is explicitly shut down, resolving the problem.
Changes:
- Replaced the unreliable `TakeUntil` wrapper with explicit stream management logic.
- Uses the same E2E test of https://github.com/infinyon/fluvio/pull/4273, but with a custom config to replicate these problematic states

fix: shutdown of the cdk consumer by future not stream

---

Cargo.lock
crates/fluvio-connector-deployer/Cargo.toml
crates/fluvio-connector-deployer/src/lib.rs
crates/fluvio-connector-deployer/src/local.rs

Related: https://github.com/infinyon/fluvio/issues/4287
```
cdk deploy start -h                                                                                                               
Start new deployment for the given connector config
Usage: cdk deploy start [OPTIONS] --config <PATH>
Options:
-c, --config <PATH>          Path to configuration file in YAML format
-s, --secrets <PATH>         Path to file with secrets. Secrets are 'key=value' pairs separated by the new line character. Optional
--ipkg <PATH>            Deploy from local package file
--log-level <LOG_LEVEL>  Log level for the connector process [default: info] [possible values: trace, debug, info, warn, error]
-h, --help                   Print help
```

fix: use info as default log level for cdk

---

release-tools/publish-crates.sh

Seems that Cargo is checking if the dependency is already uploaded before calling cargo.io.
And returning a different error that we were not expecting.
https://github.com/rust-lang/cargo/commit/6ede1e2b276eaf93618765a08bd3ec2f0f44d955
https://github.com/infinyon/fluvio/actions/runs/12332023979/attempts/1

chore: fix how check if a package is uploaded

---

crates/fluvio/Cargo.toml
crates/fluvio/src/config/tls.rs

Fixes: #4304
If openssl default feature is deactivated but rustls is active fluvio does not compile.
It complains about a missing `IoError` in `crates/fluvio/src/config/tls.rs:247`

Fixes compilation error if openssl feature is deactivated but rustls activated

---

Cargo.lock
crates/fluvio/src/consumer/stream.rs

I need that changes to be able to store dynamic `ConsumerStream` in a struct for https://github.com/infinyon/fluvio-client-python/pull/541
Remembering that we can't use generics with pyo3 structures.

chore: wrap offset_flush return in pin<box<_>>

---

crates/fluvio/src/consumer/stream.rs

I created a type for `Pin<Box<dyn Future<_>>` but I noticed now that there is `BoxFuture` that already does it.

chore: use box future

---

crates/fluvio-cluster/src/check/mod.rs

add a hints for `fluvio cluster upgrade` when a Incompatible cluster version error is raised.

add: Enhance IncompatibleLocalClusterVersion error message

---

Cargo.lock
Cargo.toml
crates/fluvio-smartengine/Cargo.toml

update smart engine to use latest wasmtime and cargo.lock

chore: update wasmtime dep for smart engine and cargo.lock

---

crates/fluvio-storage/src/bin/cli.rs
crates/fluvio-storage/src/checkpoint.rs
crates/fluvio-storage/src/replica.rs

Since HW write doesn't need to be sync with file, we can separate into  asynchronous task.
Writer task is spawned to write to file which doesn't block checkpoint update.

perf improvement: implement async write for hw checkpoint

---

crates/fluvio-benchmark/src/producer_benchmark.rs
crates/fluvio-benchmark/src/producer_worker.rs
crates/fluvio-benchmark/src/stats_collector.rs
crates/fluvio-storage/src/checkpoint.rs

chore: reorganize fluvio benchmark

---

Cargo.lock
crates/fluvio-benchmark/Cargo.toml
crates/fluvio-benchmark/src/config.rs
crates/fluvio-benchmark/src/producer_benchmark.rs
crates/fluvio-benchmark/src/producer_worker.rs
crates/fluvio-benchmark/src/stats_collector.rs
crates/fluvio-benchmark/src/utils.rs

feat: add latency table on fluvio-benchmark

---

crates/fluvio-benchmark/src/producer_benchmark.rs
crates/fluvio-benchmark/src/producer_worker.rs
crates/fluvio-benchmark/src/stats_collector.rs
crates/fluvio/src/lib.rs
crates/fluvio/src/producer/accumulator.rs
crates/fluvio/src/producer/config.rs
crates/fluvio/src/producer/mod.rs
crates/fluvio/src/producer/partition_producer.rs
crates/fluvio/src/producer/record.rs

This PR adds a callback option for the producer.
Also prints total bytes and total records per sec at the end:
```
> fluvio bench producer --batch-size 16kib --num-records 300000
27244 records sent, 27244 records/sec: (138.9 KB/sec), 1.34ms avg latency, 3.69ms max latency
37800 records sent, 37800 records/sec: (192.8 KB/sec), 1.41ms avg latency, 10.63ms max latency
42028 records sent, 42028 records/sec: (214.3 KB/sec), 1.38ms avg latency, 10.63ms max latency
41552 records sent, 41552 records/sec: (211.9 KB/sec), 1.36ms avg latency, 10.63ms max latency
40138 records sent, 40138 records/sec: (204.7 KB/sec), 1.37ms avg latency, 12.28ms max latency
40868 records sent, 40868 records/sec: (208.4 KB/sec), 1.37ms avg latency, 12.28ms max latency
40488 records sent, 40488 records/sec: (206.5 …
```

feat: add fluvio producer callback

---

crates/fluvio-storage/src/mut_index.rs

Bottleneck which is flush on index, with that remove, here is perf number:
On mac:
```
50428 records sent, 63914 records/sec: (321.0 MB/sec), 0.48ms avg latency, 4.16ms max latency
66976 records sent, 65625 records/sec: (329.6 MB/sec), 0.46ms avg latency, 5.51ms max latency
63532 records sent, 64875 records/sec: (325.8 MB/sec), 0.48ms avg latency, 6.23ms max latency
0.48ms avg latency, 6.23ms max latency, 0.46ms p0.50, 0.55ms p0.95, 0.97ms p0.99
200000 total records sent, 64516 records/sec: (324.0 MB/sec) 
Benchmark completed
```
on EC2 using C7 (4 cores/8G of memory):
```
10752 records sent, 29059 records/sec: (145.9 MB/sec), 1.00ms avg latency, 1.81ms max latency
29008 records sent, 29022 records/sec: (145.8 MB/sec), 1.01ms avg latency, 1.22ms max latency
29036 records sent, 29028 …
```

perf: improve index flush

---

Cargo.lock
Cargo.toml
crates/fluvio-socket/Cargo.toml
crates/fluvio-socket/src/multiplexing.rs

since correlation id is access indirectly,  can relax ordering

chore: relax correlation id constrain for fluvio socket

---

Cargo.toml
crates/fluvio-benchmark/src/config/mod.rs

Passing `ByteSize` as default arguments makes them been serialized and dieselized, for some reason, it converts to SI unit even we're using Bytes unit.
Solved it by passing str instead, making it been only dieselized.
Before passing 5kib it was converting to: 5100
Now passing 5kib as str is converting to 5120.
Solves: https://github.com/infinyon/fluvio/issues/4357

fix: benchmark default bytesizes

---

Cargo.lock
crates/fluvio-benchmark/Cargo.toml
crates/fluvio-benchmark/src/cli.rs
crates/fluvio-benchmark/src/config/mod.rs
crates/fluvio-benchmark/src/producer_benchmark.rs
crates/fluvio-benchmark/src/producer_worker.rs
crates/fluvio-benchmark/src/stats_collector.rs
crates/fluvio-benchmark/src/utils.rs

Should fix https://github.com/infinyon/fluvio/issues/4360

fix: benchmark dead channels

---

Cargo.lock
crates/fluvio-benchmark/Cargo.toml
crates/fluvio-benchmark/src/producer_benchmark.rs
crates/fluvio/src/producer/accumulator.rs
crates/fluvio/src/producer/record.rs

feat: add benchmark table again

---

Cargo.lock
crates/fluvio/Cargo.toml
crates/fluvio/src/producer/memory_batch.rs

Got this error testing max_request_size on python client: 
```
mymodule.PyFluvioError: record size (17 bytes), exceeded maximum request size (17 bytes)
```
Should be
```
mymodule.PyFluvioError: record size (17 bytes), exceeded maximum request size ("max_request_size" bytes)
```

fix: record too large error

---

Cargo.lock
Cargo.toml
crates/fluvio-cli/src/client/produce/mod.rs
crates/fluvio-connector-common/src/producer.rs
crates/fluvio-test/src/tests/data_generator/producer.rs
crates/fluvio/Cargo.toml
crates/fluvio/src/producer/config.rs

TopicProducerConfigBuilder was created as [owner](https://docs.rs/derive_builder/latest/derive_builder/#owned-aka-consuming), making it very difficult to handle and create wrappers for python client.
I changed this builder to the default behavior (mutable).

chore: produce config builder as mutable

---

crates/fluvio-storage/src/checkpoint.rs
crates/fluvio-storage/src/iterators.rs
crates/fluvio-storage/src/mut_index.rs
crates/fluvio-storage/src/mut_records.rs
crates/fluvio-storage/src/replica.rs
crates/fluvio-storage/src/segment.rs
crates/fluvio-storage/tests/replica_test.rs

Currently SPU allow to write to replica even if there was error occurred.   This could leads to undefined states in the storage.  This PR mark replica with flag to prevent that from happening.
This however doesn't cover all cases which need to be address in the future.
- if rollover fails, revert any changes including new segments.
Also, making logging more clear and change some logging to info as they are useful

chore: prevent batch write when storage error occurs

---

Cargo.lock
Cargo.toml
connector/sink-test-connector/src/main.rs
crates/fluvio-cli/src/client/consume/mod.rs
crates/fluvio-protocol/Cargo.toml
crates/fluvio-protocol/src/link/error_code.rs
crates/fluvio-test/src/tests/consumer_offsets/mod.rs
crates/fluvio-test/src/tests/reconnection/mod.rs
crates/fluvio/Cargo.toml
crates/fluvio/src/consumer/config.rs
crates/fluvio/src/consumer/mod.rs
crates/fluvio/src/consumer/retry.rs
crates/fluvio/src/consumer/stream.rs
crates/fluvio/src/fluvio.rs
rfc/offset-management.md

Required:
Solves https://github.com/infinyon/fluvio/issues/2167
TryForever(default):
```rust
let config = ConsumerConfigExtBuilder::default()
.topic(topic)
.retry_mode(RetryMode::TryForever)
.build()
.expect("config");
let stream = fluvio_client.consumer_with_config(config).await?
```
or just:
```rust
let config = ConsumerConfigExtBuilder::default()
.topic(topic)
.build()
.expect("config");
let stream = fluvio_client.consumer_with_config(config).await?
```
Disabled:
```rust
let config = ConsumerConfigExtBuilder::default()
.topic(topic)
.retry_mode(RetryMode::Disabled)
.build()
.expect("config");
let stream = fluvio_client.consumer_with_config(config).await?
```
Try until 10 attempts:
```rust
let config = ConsumerConfigExtBuilder::default()
.topic(topic) …
```

feat: consumer stream should be able to reconnect

---

crates/fluvio/src/consumer/mod.rs
crates/fluvio/src/consumer/retry.rs
crates/fluvio/src/consumer/stream.rs
crates/fluvio/src/fluvio.rs

I got some offset consumer tests failing sometimes, it's related to offset_commit and offset_flush have not been called on no idle or terminated states. I fixed it keeping state in the struct to be able to call it every moment.
Also, I changed the signature of `ConsumerStream` methods for wasm, making it to write async code for both.
I ran tests many times and now seems ok!

fix: commit and flush retry on other states

---

Cargo.lock
crates/fluvio-controlplane-metadata/Cargo.toml
crates/fluvio-controlplane-metadata/src/smartmodule/package.rs
crates/smartmodule-development-kit/src/generate.rs
crates/smartmodule-development-kit/src/load.rs
crates/smartmodule-development-kit/src/main.rs
crates/smartmodule-development-kit/src/publish.rs

- **fix: consistent SMARTMODULE_TOML const**
- **fix: smdk error for missing Smartmodule.toml #4412**

fix: smdk error for missing Smartmodule.toml #4412

---

Cargo.lock
Cargo.toml
crates/fluvio-cli-common/src/smartmodule.rs
crates/fluvio-cli/src/client/hub/smartmodule/download.rs
crates/fluvio-cli/src/client/remote/export.rs
crates/fluvio-cli/src/profile/sync/k8.rs
crates/fluvio-cli/src/profile/sync/local.rs
crates/fluvio-cluster/src/cli/status.rs
crates/fluvio-cluster/src/start/common.rs
crates/fluvio-cluster/src/start/k8.rs
crates/fluvio-cluster/src/start/local.rs
crates/fluvio-connector-common/src/consumer.rs
crates/fluvio-connector-common/src/producer.rs
crates/fluvio-connector-common/src/smartmodule.rs
crates/fluvio-extension-common/Cargo.toml
crates/fluvio-extension-common/src/installation.rs
crates/fluvio-extension-common/src/lib.rs
crates/fluvio-socket/Cargo.toml
crates/fluvio-socket/src/versioned.rs
crates/fluvio-test-util/setup/mod.rs
crates/fluvio/Cargo.toml
crates/fluvio/src/admin.rs
crates/fluvio/src/config/cluster.rs
crates/fluvio/src/config/config.rs
crates/fluvio/src/consumer/retry.rs
crates/fluvio/src/fluvio.rs
crates/fluvio/src/lib.rs
crates/smartmodule-development-kit/src/load.rs

Needs:
- https://github.com/infinyon/future-aio/pull/268
- https://github.com/infinyon/flv-tls-proxy/pull/34
Retry consumer was not working with consumer with a custom domain, like fluvio-web does with websocket.
This PR saves the domain connector to recreate it when needed.

fix: retry consumer with custom domain connector

---

crates/fluvio-hub-util/src/hubaccess.rs
crates/fluvio-hub-util/src/lib.rs

Export the endpoint responsible for getting the hub url, and the struct used to deserialize the response.
This is so the UIs can use it, notably here: https://github.com/infinyon/infinyon-cloud-ui/pull/1348

Export ReplyHubref{} and HUB_REF_ENDPOINT

---

crates/fluvio-spu/src/services/public/fetch_handler.rs

When we have `leader not found` error,  the details of the error is lost in the SPU

chore: change debug to warn for leader not found error and add replica id

---

crates/fluvio-hub-util/src/htclient.rs
crates/fluvio-version-manager/tests/install-fvm.sh

I did a pr based on #4437, but I'm not sure if I need to add proxy handling for `#[cfg(target_arch = "wasm32")]`as well, I don't know much about `wasm32`, feel free to discuss `wasm32` handling with me, as well as the addition of `tests`🤗

feat: add proxy on  fvm install

---

crates/fluvio-spu/src/core/global_context.rs
crates/fluvio-spu/src/kv/consumer.rs
crates/fluvio-spu/src/replication/leader/leaders_state.rs
crates/fluvio-spu/src/services/internal/fetch_consumer_offset_handler.rs
crates/fluvio-spu/src/services/internal/update_consumer_offset_handler.rs
crates/fluvio-spu/src/services/public/consumer_handler.rs
crates/fluvio-spu/src/services/public/offset_request.rs
crates/fluvio-types/src/defaults.rs
crates/fluvio/src/fluvio.rs
tests/cli/fluvio_smoke_tests/consumer-offset.bats

At https://github.com/infinyon/fluvio/pull/4448 we prefer just filter consumers with non deleted topic on list/fetch. 
But we still some problems, like https://github.com/infinyon/fluvio/issues/4455
This PR is hard deleting the consumer from the topic when topic is deleted.

fix: hard delete consumer after topic delete

---

Cargo.lock
crates/fluvio-protocol/Cargo.toml
crates/fluvio-protocol/src/fixture.rs
crates/fluvio-protocol/src/record/batch.rs
crates/fluvio-protocol/src/record/data.rs
crates/fluvio-spu/Cargo.toml
crates/fluvio-spu/src/config/cli.rs
crates/fluvio-spu/src/replication/test.rs
crates/fluvio-storage/src/batch.rs
crates/fluvio-storage/src/replica.rs
crates/fluvio-storage/src/segment.rs
crates/fluvio-types/src/defaults.rs

Should fix replica sync problem: https://github.com/infinyon/fluvio/issues/4472
I also notice more perfomance with replicas now:
before:
```
fluvio benchmark producer -p 3 -r 3 -k --num-records 50000                                                                                                                                                                                                                                                              $ fix_replication_large_2 
Benchmark started
latencies: 19.7µs min, 7.4ms avg, 33.1ms max, 7.2ms p0.50, 15.1ms p0.95, 17.3ms p0.99
50000 total records sent, 71942 records/sec: (369.1 MB/sec), total time: 695.9ms
**Per Record E2E Latency**
|Variable| p0.00 |p0.50|p0.95 |p0.99 |p1.00 |
|--------|-------|-----|------|------|------|
|Latency …
```

fix: replication stuck when syncing large batches

---

crates/fluvio-types/src/defaults.rs

1gb was using too much memory, and performance was worse.

chore: set SPU_PEER_MAX_BYTES to 10mb

---

crates/fluvio/src/spu.rs

`TopicProducerPool` cannot be cloned due to this limitation.

fix: derive clone on SpuSocketPool

---

Cargo.lock
crates/fluvio/Cargo.toml
crates/fluvio/src/consumer/mod.rs
crates/fluvio/src/consumer/retry.rs
crates/fluvio/src/fluvio.rs

BoxedConsumerStream is handy.  This moves into core part of consumer stream to make it easier to use it

chore: move boxed stream into main consumer api

---

crates/fluvio-cli-common/src/smartmodule.rs
smartmodule/examples/Cargo.lock
smartmodule/examples/Cargo.toml
smartmodule/examples/filter_odd_key/Cargo.toml
smartmodule/examples/filter_odd_key/src/lib.rs
tests/cli/smdk_smoke_tests/smdk-basic.bats

Should solve https://github.com/infinyon/fluvio/issues/4497
Currently, the key is the first and unique argument, which is odd. I changed to a named parameter.
Currently:
```
smdk test --text="Open" 123
```
With this PR:
```
smdk test --text="Open" --key 123
```

chore: add key record parameter to smdk test

---

crates/fluvio-cli/README.md
crates/fluvio-cli/src/client/topic/describe.rs

Remove outdated Kafka compatibility reference from README.

---

crates/fluvio-spu-schema/src/server/fetch_offset.rs
crates/fluvio-spu/src/services/public/offset_request.rs

I forgot to rename these comments to `FetchConsumerOffsetsRequest` in https://github.com/infinyon/fluvio/pull/4500

chore: use right offset request in comments

---

crates/fluvio-test/src/tests/consumer_offsets/auto/flush.rs
crates/fluvio/src/consumer/config.rs
crates/fluvio/src/consumer/mod.rs
crates/fluvio/src/consumer/retry.rs
crates/fluvio/src/consumer/stream.rs
tests/cli/fluvio_smoke_tests/consumer-offset.bats

Should solve https://github.com/infinyon/fluvio/issues/4505 and https://github.com/infinyon/fluvio/issues/4324
This PR:
- Adding background checker for offset management when `Auto` is the strategy, before were only checking if should flush or not when receive a new record.
- Improve drop of consumer stream
- Clean up `ConsumerRetryStream`

fix: auto management odd pauses in consumer offset

---

k8-util/helm/fluvio-app/templates/sc-deployment.yaml

While testing fluvio I found that the extra volumes are not rendered in the correct place. This PR fixed that.
Additionally, I've added support to render extra volume mounts when no TLS config is provided.

fix: render extra volumes under the volumes property

---

Cargo.lock
crates/fluvio-protocol/Cargo.toml
crates/fluvio-protocol/src/record/batch.rs

Similar to https://github.com/infinyon/fluvio/pull/4474, but for consume.
Solves https://github.com/infinyon/fluvio/issues/4523
In others places like `RecordSet` we have `Batch<RawRecords>` and we ignore errors of `UnexpectedEof`, because we can receive uncompleted records limited by max_bytes.
For consuming, we handle records with `ConsumerRecord` that is created by converting `Batch<RawRecords>` to `Batch<MemoryRecords>`. So we need to ignore these errors here too.

fix: consume large and incomplete batches

---

Cargo.toml
crates/cdk/Cargo.toml
crates/fluvio-cli-common/Cargo.toml
crates/fluvio-cli/Cargo.toml
crates/fluvio-connector-common/Cargo.toml
crates/fluvio-connector-package/Cargo.toml
crates/fluvio-hub-util/Cargo.toml
crates/fluvio-protocol/Cargo.toml
crates/fluvio-run/Cargo.toml
crates/fluvio-smartmodule/Cargo.toml
crates/fluvio-test-derive/Cargo.toml
crates/fluvio-test-util/Cargo.toml
crates/fluvio-test/Cargo.toml
crates/smartmodule-development-kit/Cargo.toml

Also fixing these warnings:
```
warning: /Users/frai/workspace/infinyon/fluvio/crates/fluvio-smartmodule/Cargo.toml: unused manifest key: dependencies.fluvio-smartmodule-derive.path
warning: /Users/frai/workspace/infinyon/fluvio/crates/fluvio-protocol/Cargo.toml: unused manifest key: dependencies.fluvio-compression.path
warning: /Users/frai/workspace/infinyon/fluvio/crates/fluvio-protocol/Cargo.toml: unused manifest key: dependencies.fluvio-protocol-derive.path
```

chore: centrilize paths in root Cargo.toml

---

crates/fluvio-protocol/src/core/encoder.rs
crates/fluvio-protocol/src/record/data.rs
crates/fluvio-protocol/tests/str.rs

This add support for encoding string slice using fluvio protocol.   This can be used for high performance encoding of string.
Also add some helper for to convert back record key into record data

utility: add support for encoding string slice

---

Cargo.lock
Cargo.toml
crates/fluvio/Cargo.toml
crates/fluvio/src/config/tls.rs
crates/fluvio/src/fluvio.rs

Rustls is tricky to handle when an application is using more than one crypto provider.
When more than one provider is enabled, we have these errors: 
```
no process-level CryptoProvider available -- call CryptoProvider::install_default() before this point
```
Easily to have more than one provider enable if using sub library from rustls ecosystem that only support one of them.
~This PR is adding a new feature for Fluvio crate called `rustls-ring` to use ring provider instead of `aws-ls-rs`. That way we'll have sure that one is settled at least and control it by feature flags.~
This PR is adding two new feature for Fluvio crate called `ring` and `aws-ls-rs`. `aws-ls-rs` is the default.
That way we'll have sure that one is settled at least and control it by feature flags.

chore: ensure that crypto provider is set
