infinyon/fluvio

- DEVELOPER.md
- Cross compilations issues while make minikube image
- Added troubleshooting guide
> Updated docs to reflect missing steps

- CODE-OF-CONDUCT.MD
- CONTRIBUTING.md
- README.md
> Added Contribution guide and Code of conduct.

- .cargo/config
> Support 32-bit ARM (armv7-unknown-linux-gnueabihf)

- website/docs/profiles.md
- Added Profile operations
- Added Basic cluster details
> Updated profiles file

- src/cli/src/cluster/install/local.rs
Fixes #32 
Changed the respective log locations for SC and SPU based on OS
- macos: /usr/local/var/log/fluvio
- linux: /var/log/fluvio
> Changed default log location for SC and SPU logs depending on OS.

- src/cli/src/cluster/install/helm.rs
- src/cli/src/cluster/install/k8.rs
- src/cli/src/cluster/install/mod.rs
> Check if version is available in fluvio helm repo before proceeding to install

- website/docs/_index.md
Updated with latest fluvio operations
> Updated index file

- website/kubernetes/INSTALL.md
> Added troubleshooting section to installation guide

- src/cli/Cargo.toml
- src/cli/src/cluster/install/local.rs
- src/cli/src/cluster/uninstall.rs
- src/cli/src/cluster/util.rs
- tests/runner/src/environment/local.rs
- tests/runner/src/util/cmd.rs
use fluvio to launch sc and spu
test: spawin installation
> cli: make cluster_components as default feature

- src/cli/src/lib.rs
- src/cli/src/tls/mod.rs
- src/cli/src/topic/create.rs
- website/docs/_index.md
- Also updated relevant documentation.
- Will send separate PR for fluvio-website for documentation updates.
> Updated 'fluvio topic create' command

- src/event-stream-k8/src/dispatcher/k8_dispatcher.rs
- src/event-stream-model/src/store/k8.rs
- src/metadata-cluster/src/partition/mod.rs
- src/metadata-cluster/src/spg/mod.rs
- src/metadata-cluster/src/spu/mod.rs
- src/metadata-cluster/src/topic/mod.rs
make K8EnhancedSpec to make it more flexible for conversion
> update k8 dispatcher to skip incoming k8 objects

- src/cli/src/cluster/install/k8.rs
- src/cli/src/cluster/install/mod.rs
- src/cli/src/cluster/util.rs
- tests/runner/src/util/cmd.rs
> Showing detailed error message when sys chart installation fails

- src/cli/src/cluster/minikube.rs
- src/sc-k8/src/init.rs
- src/sc-k8/src/operator/mod.rs
- src/sc-k8/src/operator/spg_operator.rs
- src/sc-k8/src/operator/svc_operator.rs
restore code to update spu's public ip address for svc operator
> resolve issue #122

- src/cli/src/cluster/uninstall.rs
> Implemented uninstall command to remove fluvio sys chart.

- Cargo.lock
- src/cli/Cargo.toml
- src/cli/src/cluster/install/k8.rs
> Checking if the server details in cluster has IP address.

- src/cli/src/cluster/install/helm.rs
- src/cli/src/cluster/install/k8.rs
- src/cli/src/cluster/install/mod.rs
respect --version when installing chart version for both dev and release
add  --chart-location for both dev and release
> implement: #146

- src/cli/src/cluster/install/k8.rs
Fixes #161 
- Implemented logic to fix: pre_install_check fails when running from inside K8 Pod
> Changes for following issue:

- DEVELOPER.md
- Updated troubleshooting section
> Updated Developer guide

- Cargo.lock
- src/cli/Cargo.toml
- src/cli/src/bin/main.rs
- src/cli/src/lib.rs
- src/cli/src/profile/mod.rs
- src/cli/src/profile/sync/cloud/login_agent.rs
- src/cli/src/profile/sync/cloud/mod.rs
- src/metadata-cluster/Cargo.toml
In #157 we added the ability to authenticate with Fluvio Cloud, this PR adds the ability to download profiles.
Example flow:
```
$ fluvio profile sync cloud
Fluvio Cloud email: mosher@infinyon.com
Password: <hidden>
$ fluvio profile current
fluvio-cloud
```
> Download and save Fluvio Cloud profile

- .github/workflows/ci.yml
- Makefile
- tests/runner/src/tests/smoke/message.rs
Before checking in your work, run `make check-clippy`
> use make file for clippy check

- .github/workflows/ci.yml
> Add TLS smoke tests to CI

- src/cli/src/cluster/install/k8.rs
- src/cli/src/cluster/install/mod.rs
add registry option for cluster install for testing out #185
> consolidated k8 install to reduce duplication

- .github/workflows/latest.yml
- k8-util/helm/fluvio-core/Chart.yaml
update fluvio core chart to 0.6.0-latest
> add helm publish chart to latest workflow

- .github/workflows/publish_latest.yml
- k8-util/helm/fluvio-sys/Chart.yaml
> update fluvi-sys chart version to match fluvio-core

- .github/workflows/publish_latest_chart.yml
- .github/workflows/publish_latest_docker.yml
- Makefile
- k8-util/helm/Makefile
- k8-util/helm/fluvio-app/Chart.yaml
update makefile for publishing helm
> rename docker publish and separate out helm chart

- k8-util/helm/Makefile
- src/cli/src/cluster/install/helm.rs
- src/cli/src/cluster/install/k8.rs
- src/cli/src/cluster/install/mod.rs
with this change, CLI can customize chart and image location separately.
> update CLI to deploy charts from helm repository

- Cargo.lock
- src/client-rs/Cargo.toml
- src/client-rs/src/client/client.rs
- src/client-rs/src/consumer.rs
- src/client-rs/src/producer.rs
- src/client-rs/src/spu/spu_pool.rs
add serial_socket for shared spu pool.
> implement spu pool

- Makefile
- tls/Makefile
move tls related task to tls directory
> simplify makefile

- src/client-rs/src/consumer.rs
- src/client-rs/src/spu/spu_pool.rs
- src/client-rs/src/sync/store.rs
- src/kf-socket/src/multiplexing.rs
> update to client spu pool API

- .github/workflows/publish_nightly_docker.yml
- Makefile
change latest to publish on every commit
> add nightly docker image workflow

- src/client-rs/src/sync/mod.rs
- tests/runner/src/test_runner.rs
increase delay after topic creation during CI run
> fix flaky test run

- Cargo.lock
- src/client-rs/Cargo.toml
- src/client-rs/src/sync/mod.rs
- src/event-stream-model/Cargo.toml
- src/event-stream-model/src/store/concurrent_hashmap.rs
- src/event-stream-model/src/store/store.rs
- src/spu-server/Cargo.toml
- src/spu-server/src/controllers/leader_replica/leader_controller.rs
- src/spu-server/src/controllers/leader_replica/leaders_state.rs
- src/spu-server/src/controllers/sc/dispatcher.rs
- src/spu-server/src/error.rs
- src/spu-server/src/lib.rs
> convert to use async rw-lock for SPU leader state

- .github/workflows/ci.yml
fixes https://github.com/infinyon/fluvio/issues/256
> add cargo cvm check to ci

- .github/workflows/ci.yml
- DEVELOPER.md
- Makefile
- k8-util/docker/sc/Makefile
- k8-util/docker/spu/Makefile
Added CI steps for running in Mac (disabled for now).
Build images directory to docker
> add mac os to CI smoke test

- .github/workflows/ci.yml
Separate out local cluster from k8 cluster test.
> Run mac ci

- Cargo.lock
- Cargo.toml
- Makefile
- src/cli/Cargo.toml
- src/client/Cargo.toml
- src/cluster/Cargo.toml
- src/controlplane-metadata/Cargo.toml
- src/kf-service/Cargo.toml
- src/kf-socket/Cargo.toml
- src/kf-socket/src/multiplexing.rs
- src/sc-schema/Cargo.toml
- src/sc/Cargo.toml
- src/spu/Cargo.toml
- src/storage/Cargo.toml
- src/stream-dispatcher/Cargo.toml
- src/stream-model/Cargo.toml
this fixes issue where log doesn't appear in unit tests
> update to use flv-util 0.4.0

- Cargo.lock
- Cargo.toml
- Makefile
- dev-tools/README.md
- dev-tools/log/debug-sc-all
- dev-tools/log/debug-sc-min
- dev-tools/log/debug-spu-all
- dev-tools/log/debug-spu-min
- src/client/Cargo.toml
- src/controlplane-metadata/Cargo.toml
- src/controlplane/Cargo.toml
- src/controlplane/src/sc_api.rs
- src/controlplane/src/spu_api.rs
- src/kf-service/Cargo.toml
- src/kf-service/src/test_request.rs
- src/kf-socket/Cargo.toml
- src/kf-socket/src/test_request.rs
- src/kf-socket/tests/enum.rs
- src/sc-schema/Cargo.toml
- src/sc-schema/src/apis.rs
- src/sc/Cargo.toml
- src/spu-schema/Cargo.toml
- src/spu-schema/src/client/api_key.rs
- src/spu-schema/src/server/api_key.rs
- src/spu/Cargo.toml
- src/spu/src/controllers/follower_replica/api_key.rs
- src/spu/src/controllers/leader_replica/api_key.rs
- src/spu/src/services/internal/api.rs
- src/storage/Cargo.toml
- tests/runner/Cargo.toml
to fix issue: https://github.com/infinyon/flv-kf-protocol/issues/22
> update to use kf-protocol with fixed enum conversion

- k8-util/crd/config/gp2-storageclass-spu.yaml
- k8-util/crd/config/local-storageclass.yaml
- k8-util/crd/config/minikube-storageclass-spu.yaml
- k8-util/crd/config/persistent_volume_claim_spu.yaml
- k8-util/helm/fluvio-sys/templates/storage.yaml
- src/cli/src/cluster/uninstall.rs
Having some issues with my local fluvio cluster install, so I haven't tested this yet.
> add storageclass label to storage class and pvcs

- src/cli/src/lib.rs
- src/spu/src/lib.rs
> update type length limit

- .github/workflows/publish_latest_chart.yml
Resolves https://github.com/infinyon/fluvio/issues/217
Requires `HELM_PASSWORD` secret to be set
> Update workflow to push Helm charts to charts.fluvio.io

- .github/workflows/ci.yml
- Makefile
set default mac driver for minikube to be `virtual box` to make it reliable
change back consumer test's iteration = 1 to make TLS test works
> disabel TLS in CI

- src/cluster/src/helm.rs
- src/cluster/src/install.rs
Fixes #307 
Checks for existing fluvio installation and warns the user.
> Check if cluster is already installed and show appropriate error message

- src/cli/src/cluster/install/k8.rs
- src/cli/src/cluster/install/local.rs
- src/cli/src/cluster/install/mod.rs
- src/cli/src/cluster/install/tls.rs
- src/cli/src/lib.rs
- src/cli/src/profile/context.rs
- src/cli/src/profile/k8.rs
- src/cli/src/profile/sync/mod.rs
- src/cli/src/tls/mod.rs
> Fix TLS opts not being used in CLI install

- Cargo.lock
- src/cluster/Cargo.toml
- src/cluster/src/error.rs
- src/cluster/src/helm.rs
This introduces just the helm portion of the changes introduced in #325
> Add better error messages for helm

- src/cli/src/cluster/install/local.rs
- src/controlplane-metadata/src/spu/spec.rs
>  Changes for smoke-test to use "custom" instead of "managed" spu

- Cargo.lock
- src/cli/Cargo.toml
- src/client/src/admin.rs
- src/controlplane-metadata/Cargo.toml
- src/controlplane/Cargo.toml
- src/sc/Cargo.toml
- src/spu/Cargo.toml
- src/storage/Cargo.toml
- src/stream-dispatcher/Cargo.toml
- src/stream-model/Cargo.toml
- src/stream-model/src/store/store.rs
- src/utils/Cargo.toml
- tests/runner/Cargo.toml
cleanup mutable for admin
rename utils as fluvio-system-util
> add missing version and descriptions

- .github/workflows/publish_latest_docker.yml
- .github/workflows/publish_nightly_docker.yml
- Makefile
- Move publishing latest and nightly image from GitHub Actions to Makefile
- Consolidate and clean up Makefile steps
> update makefile to consolidate steps for publish docker images

- src/cli/src/profile/sync/cloud/mod.rs
> Switch to fluvio-cloud context after login

- src/cli/src/cluster/check.rs
> Fixed duplicate crd . Replaced typo with ServiceAccount

- Cargo.lock
- src/sc/Cargo.toml
- src/stream-dispatcher/Cargo.toml
- src/stream-dispatcher/src/dispatcher/k8_dispatcher.rs
- src/stream-dispatcher/src/error.rs
- tests/runner/Cargo.toml
- tests/runner/src/tests/smoke/consume.rs
remove SendError from Error types from stream-dispatcher
bump up sc and stream-dispatcher cargo version
> remove futures library

- Makefile
- src/spu/src/controllers/sc/dispatcher.rs
- src/storage/src/mut_records.rs
- tests/README.md
- tests/runner/src/tests/smoke/consume.rs
remove unneeded validation in the consumer test
> add default iteration to be 100 for smoke test

- .github/ISSUE_TEMPLATE/bug_report.md
Adds the default Bug report issue template from GH with slight modifications
> Add bug issue templates

- tests/TEST_CASE.md
update TEST_CASE.md in the test runner folder
> add test case for election test

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- Makefile
- src/cli/Cargo.toml
- src/client/Cargo.toml
- src/client/src/admin.rs
- src/client/src/client/client.rs
- src/client/src/client/cluster.rs
- src/client/src/config/tls.rs
- src/sc/Cargo.toml
- src/spu/Cargo.toml
- src/storage/Cargo.toml
- bump up major versions for `cli`,`spu`,`sc`
- add TLS feature flag for `client`.
-add support for native TLS for client
> add native tls for client

- Cargo.lock
- Makefile
- src/cli/Cargo.toml
- src/cli/src/cluster/install/mod.rs
- src/cli/src/lib.rs
- src/cli/src/profile/k8.rs
- src/cli/src/profile/mod.rs
- src/cli/src/root_cli.rs
- src/client/Cargo.toml
- src/cluster/Cargo.toml
- src/cluster/src/check.rs
- src/cluster/src/install.rs
- src/cluster/src/uninstall.rs
- src/sc/Cargo.toml
- src/sc/src/lib.rs
- src/spu/Cargo.toml
Default to native k8-client except for pods
> switch over to use native k8-client

- src/cli/LICENSE-APACHE
- src/controlplane/LICENSE-APACHE
- src/package-index/Cargo.toml
- src/package-index/LICENSE-APACHE
- src/sc/LICENSE-APACHE
- src/spu/LICENSE-APACHE
- src/storage/LICENSE-APACHE
- src/stream-dispatcher/LICENSE-APACHE
- src/stream-model/LICENSE-APACHE
- src/types/LICENSE-APACHE
- src/utils/LICENSE-APACHE
This adds the required metadata to publish to crates.io
> Add package metadata for fluvio-package-index

- .github/workflows/ci.yml
- Cargo.lock
- src/cli/Cargo.toml
- src/client/Cargo.toml
- src/client/src/admin.rs
- src/client/src/client/client.rs
- src/client/src/client/cluster.rs
- src/client/src/spu/spu_pool.rs
- src/client/src/sync/controller.rs
- src/client/src/sync/store.rs
- src/cluster/Cargo.toml
- src/sc/Cargo.toml
- src/sc/src/k8/service/controller.rs
- src/stream-dispatcher/Cargo.toml
- src/stream-dispatcher/src/store/mod.rs
use 0.4.0 of fluvio socket
force resend of service controller in the sc
use polling for store dispatcher sync instead of just listener
> use 0.4.0 of fluvios-socket in the client

- Makefile
- src/cli/src/consume/mod.rs
- src/client/src/spu/spu_pool.rs
- src/client/src/sync/mod.rs
reduce time for looking up replica to 300 ms
return proper error code instead of timeout
> reduce timeout for searching replica

- src/sc/src/services/public_api/topic/create.rs
fix proper error when trying to create duplicate topic
> if there is topic creation error return proper error

- .github/workflows/ci.yml
- Makefile
- src/cluster/src/install.rs
- src/sc/src/controllers/topics/controller.rs
- tests/runner/src/test_runner.rs
- tests/runner/src/tests/smoke/consume.rs
- tests/runner/src/tests/smoke/message.rs
- tests/runner/src/tests/smoke/produce.rs
- force to resync topic controller every 60 seconds
- better debug message during consumer validation
- wait until test running shutdown to allow logs to catch up
- set client logging level to warn
- remove macOS from CI local cluster test
> more changes to make it CI stable

- Cargo.lock
- src/client/Cargo.toml
- src/client/src/sync/mod.rs
- src/cluster/src/install.rs
- src/sc/Cargo.toml
- src/sc/src/controllers/topics/controller.rs
- src/sc/src/services/public_api/spg/create.rs
- src/spu/src/controllers/leader_replica/leader_controller.rs
- src/stream-dispatcher/Cargo.toml
- src/stream-dispatcher/src/dispatcher/k8_dispatcher.rs
- src/types/src/defaults.rs
- add more structure logging if few places
- update to stream dispatcher to use updated timer
> various cleanup

- Cargo.lock
- Cargo.toml
- Makefile.toml
- src/client/Cargo.toml
- src/client/src/admin.rs
- src/client/src/client/client.rs
- src/client/src/client/cluster.rs
- src/client/src/config/tls.rs
- src/dataplane-protocol/Cargo.toml
Use `cfg_if!` to configure TLS in the crates. 
Update to latest `fluvio-socket`
> update the TLS configurations to build under all features

- .github/workflows/ci.yml
- Makefile
- src/cli/src/cluster/install/k8.rs
- src/cli/src/cluster/install/local.rs
- src/cli/src/cluster/install/mod.rs
- src/cluster/src/check.rs
- src/cluster/src/install.rs
- src/cluster/src/local.rs
-Integrated with CI
~~I am testing the changes currently~~
> Added a new flag that sets up installation environment for k8 and local

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- Makefile
- src/cluster/Cargo.toml
- src/cluster/src/install.rs
> try to fix k8 test by disabling LTO

- .github/workflows/ci.yml
- Makefile
enabled TLS auth test in the ci
fix the TLS auth test for k8
> Run TLS auth test in the CI

- .github/workflows/ci.yml
- Makefile
- src/sc/src/controllers/topics/controller.rs
Instead of sleeping 60 seconds between each loop, it is only done once.
> fix topic controller not sleeping properly

- .github/workflows/ci.yml
- Makefile
> improve unit test time in the CI using sccache

- src/cli/src/bin/main.rs
- src/cli/src/lib.rs
Closes #526. A bit hacky on getting the default route. I couldn't figure out how to specify no parameters to clap or structopt.
> Added extensions to help section of fluvio

- .github/workflows/release.yml
- Makefile
- Makefile.toml
- makefiles/Base.toml
- makefiles/Github.toml
- makefiles/Pi.toml
- makefiles/S3.toml
I forgot that releases workflows can only run from a branch in the same repo.
This is the same PR as #530 and will close #465.
> Fluvio publish in release workflow

- src/cli/src/bin/main.rs
Minor mistake with the exit code in in #547.
> Fixed help exit code

- src/cluster/src/check.rs
- src/cluster/src/cli/check.rs
Fixes the first point of #560 
Checks may now offer suggestions to fix the thing that went wrong. This looks like the following:
> Allow checks to provide suggestions

- Cargo.lock
- src/stream-dispatcher/Cargo.toml
- src/stream-dispatcher/src/store/mod.rs
for update, wait for update instead of just returning immediately
> fix create_spec in stream-model

- Cargo.lock
- src/cluster/Cargo.toml
- src/cluster/src/cli/start/local.rs
- src/cluster/src/start/k8.rs
- src/cluster/src/start/local.rs
- src/cluster/src/start/mod.rs
> Use published helm charts for local sys install

- src/cluster/src/cli/spu/list.rs
> Fix CLI printing duplicate Spu

- Cargo.lock
- Makefile
- src/cluster/src/delete.rs
- src/dataplane-protocol/src/error_code.rs
- src/sc/Cargo.toml
- src/sc/src/services/public_api/topic/create.rs
- tests/runner/src/test_runner.rs
Ensure topic are fully provisioned when created.
Remove topic wait in the tester
Make partition delete more robust
> Wait topic creation

- Cargo.lock
- src/client/Cargo.toml
- src/client/src/sync/controller.rs
- src/client/src/sync/mod.rs
- src/controlplane-metadata/Cargo.toml
- src/sc-schema/Cargo.toml
- src/sc-schema/src/lib.rs
convert event listener to use change listener
bump up sc-schema to include metadata
> make fluvio client partition look up more reliable

- src/cli/src/install/mod.rs
- src/cli/src/install/update.rs
> Fix self update

- .github/workflows/release.yml
- makefiles/Github.toml
- makefiles/S3.toml
Defaults to nothing, forces a new release only if ran with `--force`.
> Adding force dispatch argument to release CI

- .github/workflows/release.yml
- makefiles/Pi.toml
I wasn't finished testing and fixing the force releases when #599 was merged. This one is [good to go](https://github.com/infinyon/fluvio/actions/runs/439020636).
> Fix force releases

- .github/workflows/ci.yml
- actions/action-install-minikube.sh
This is a partial fix to infinyon/fluvio-client-node#42 CI. This will also close #570.
> Updated the minikube driver to docker rather than none

- Cargo.lock
- Cargo.toml
- k8-util/helm/fluvio-app/templates/role.yaml
- k8-util/helm/fluvio-app/templates/sc-deployment.yaml
- k8-util/helm/fluvio-app/templates/spu-k8-config.yaml
- k8-util/helm/fluvio-app/values.yaml
- src/sc/src/k8/operator/conversion.rs
- src/sc/src/k8/operator/mod.rs
- src/sc/src/k8/operator/spg_operator.rs
- src/sc/src/k8/operator/spu_k8_config.rs
Resolves https://github.com/infinyon/fluvio/issues/543
> SC and SPU resource config

- src/spu/src/controllers/leader_replica/replica_state.rs
- src/spu/src/controllers/sc/message_sink.rs
fix dispatche channel update by using replace instead of add
> fix partition offset update in sc

- Cargo.lock
- src/cluster/Cargo.toml
- src/cluster/src/start/k8.rs
make sc dns and network wait to be constant and make it configurable.
use stream iterator to wait for sc address instead of using polling
> fix cluster installer to use constant wait

- src/cluster/src/lib.rs
- src/cluster/src/start/k8.rs
Resolves https://github.com/infinyon/fluvio/issues/543
> Add resource requirements config to cluster installer

- k8-util/helm/fluvio-sys/Chart.yaml
- k8-util/helm/fluvio-sys/templates/storage.yaml
this force K8 to delete volume associated with PVC
> set minikube's pvc to use delete instead of reclaim

- src/client/src/client/cluster.rs
- src/client/src/spu/spu_pool.rs
- src/client/src/sync/store.rs
> Added FluvioInner to Fluvio and dependent structs.

- .github/workflows/release.yml
- makefiles/Github.toml
- makefiles/Pi.toml
I cannot get [this release failure to reroduce on my local machine](https://github.com/infinyon/fluvio/runs/1665114390?check_suite_focus=true).
> Fix non-forced release CI

- src/command/Cargo.toml
- src/command/LICENSE-APACHE
@sehz let me know if there are any more required fields but I copied the ones that were in CLI so I think this should be good.
> Add manifest info for publishing to fluvio-command

- src/cluster/Cargo.toml
Fix dependency on fluvio-command
> Add version dep of fluvio-command to fluvio-cluster

- src/cli/src/install/mod.rs
Removed Err return
Resolves #718
> Create basedir during `fluvio install` if missing

- Cargo.lock
- Makefile
- src/auth/Cargo.toml
- src/client/Cargo.toml
- src/controlplane-metadata/Cargo.toml
- src/controlplane/Cargo.toml
- src/dataplane-protocol/Cargo.toml
- src/dataplane-protocol/src/record.rs
- src/sc-schema/Cargo.toml
- src/sc/Cargo.toml
- src/sc/src/services/private_api/mod.rs
- src/sc/src/services/private_api/private_server.rs
- src/sc/src/services/public_api/mod.rs
- src/sc/src/services/public_api/public_server.rs
- src/service/Cargo.toml
- src/socket/Cargo.toml
- src/socket/src/multiplexing.rs
- src/socket/src/socket.rs
- src/socket/src/stream.rs
- src/spu-schema/Cargo.toml
- src/spu/Cargo.toml
- src/spu/src/services/internal/mod.rs
- src/spu/src/services/internal/service_impl.rs
- src/spu/src/services/public/mod.rs
- src/spu/src/services/public/service_impl.rs
- src/storage/Cargo.toml
I think this is a follow up from #749.
> Updated dependencies on socket,service and protocol to use path

- Cargo.lock
- src/cluster/Cargo.toml
- src/command/Cargo.toml
- src/command/src/lib.rs
> Revert "Updates CommandExt to capture stdout and stderr in error types"

- Cargo.lock
- src/cluster/Cargo.toml
- src/command/Cargo.toml
- src/command/src/lib.rs
> Revert "Revert "Updates CommandExt to capture stdout and stderr in error types""

- .github/workflows/ci.yml
hopefully this will make k8-test less flaky
> increase timeout for k8-workflow

- src/cluster/src/cli/group/create.rs
- src/controlplane-metadata/src/topic/spec.rs
- src/protocol/fluvio-protocol-api/src/request.rs
- src/sc-schema/src/objects/delete.rs
- src/sc-schema/src/objects/list.rs
- src/sc-schema/src/objects/watch.rs
- src/sc/build.rs
- src/sc/src/config/sc_config.rs
- src/sc/src/k8/operator/spg_operator.rs
- src/storage/src/index.rs
Rust 1.50.0 introduces new clippy lints that need fixing, this PR should fix them and stop our clippy CI from failing
> Fix new clippy lints

- .github/workflows/ci.yml
- k8-util/helm/fluvio-app/templates/sc-deployment.yaml
- src/cluster/src/delete.rs
Resolves https://github.com/infinyon/fluvio/issues/779
> Convert SC to Deployment

- Cargo.lock
- src/cli/Cargo.toml
- src/client/Cargo.toml
- src/cluster/Cargo.toml
- src/extension-common/Cargo.toml
- src/extension-consumer/Cargo.toml
I think we only need to bump the client crate.
> updated to 0.5.0-beta.1

- Cargo.lock
- src/cli/Cargo.toml
- src/cluster/Cargo.toml
- src/sc/Cargo.toml
- src/stream-model/Cargo.toml
Follow up to https://github.com/infinyon/fluvio/pull/794 which was incomplete
> Bump K8 API affected crates

- Cargo.lock
- src/cluster/Cargo.toml
- src/extension-runner-local/Cargo.toml
- src/sc/Cargo.toml
- src/sc/build.rs
- src/sc/src/lib.rs
Reverts of the stuff for #723 to allow for publishing of the `sc` crate.
> Added platform flag for sc

- Cargo.lock
- src/cli/Cargo.toml
- src/cli/build.rs
- src/cli/src/lib.rs
> Remove rustc version printout from 'fluvio version'

- .github/workflows/ci.yml
- Cargo.lock
- src/cluster/src/start/k8.rs
- src/types/Cargo.toml
- src/types/src/event.rs
Optimize offset event publisher by reducing  a single atomic operation during listen instead of 2
> optimize offset event publisher

- .github/workflows/ci.yml
- src/cluster/src/start/k8.rs
- tests/runner/src/environment/k8.rs
Make Version check configurable and add more diagnostic when there is failure
> Make k8 job on  CI more reliable

- .github/workflows/release.yml
Fixes release workflow for 0.7.1
> Disabled pi releases for now

- Cargo.lock
- src/spu/Cargo.toml
- src/spu/src/lib.rs
update  rust dependencies
add explicit dependencies to unix for SPU
> make SPU friendly to rust compilers

- Makefile
- src/auth/src/error.rs
- src/cluster/src/lib.rs
- src/storage/src/bin/cli.rs
- src/stream-dispatcher/src/dispatcher/k8_dispatcher.rs
- src/stream-model/src/store/metadata.rs
Rust 1.51 introduced new lints to fix
> Fix clippy lints

- .github/workflows/ci.yml
- Cargo.lock
- Makefile
- src/command/src/lib.rs
- src/protocol/fluvio-protocol-derive/Cargo.toml
- src/protocol/fluvio-protocol-derive/src/lib.rs
For #735.
This fails for me locally, but maybe OS specific error.
> Add doc test job to CI

- .github/workflows/publish_latest_chart.yml
I need this merged so that it starts publishing helm charts with the same version scheme as the Fluvio CLI. Please let me know if there is anything that needs to be changed :)
> Update helm chart publish version with git commit

- Cargo.lock
- Makefile
remove unnecessary clippy check as well
> update dependencies to latest

- .github/workflows/publish_latest_chart.yml
- .github/workflows/publish_latest_fluvio.yml
This disables publishing latest _helm charts_ rather than _Fluvio CLI_
> Whoops disabled wrong workflow

- .github/workflows/hourly.yml
Workflow dispatch only for now
> Disable hourly job schedule

- .github/workflows/ci.yml
- .github/workflows/ci_mac.yaml
- bors.toml
Replace Bors with GH merge queue
> CI: Enable `merge_group` event in CI

- .github/workflows/cd_dev.yaml
- .github/workflows/ci.yml
- .github/workflows/hourly.yml
- crates/fluvio-cli/src/profile/add.rs
- crates/fluvio-cli/src/profile/list.rs
- crates/fluvio-cluster/src/check/mod.rs
- crates/fluvio-cluster/src/cli/delete.rs
- crates/fluvio-cluster/src/cli/diagnostics.rs
- crates/fluvio-cluster/src/cli/shutdown.rs
- crates/fluvio-cluster/src/cli/start/local.rs
- crates/fluvio-cluster/src/cli/start/mod.rs
- crates/fluvio-cluster/src/delete.rs
- crates/fluvio-cluster/src/lib.rs
- crates/fluvio-cluster/src/start/k8.rs
- crates/fluvio-cluster/src/start/local.rs
- crates/fluvio-spu/Makefile
- crates/fluvio-test-util/setup/environment/local.rs
- crates/fluvio/src/config/config.rs
- tests/cli/fluvio_read_only/basic.bats
- tls/Makefile
This reverts commit 3d87bf18f92c3a5438e2316c8fccc638f656bf6f.
CI was unstable when this was merged, need to revert to get back to a stable master
> Revert "feat: use installation type in cli commands (#3675)"

- .github/workflows/ci.yml
- tests/upgrade-test.sh
Fix paths and small details that was causing k8 and cli smoke tests to fail
> ci: Misc fixes to failing tests in CI

- .github/workflows/cd_dev.yaml
- .github/workflows/cd_release.yml
more test harness fixups due to fvm output changes vs old fluvio installer
> chore: ci fix cd_dev and cd_release

- crates/fluvio-version-manager/src/command/itself/install.rs
- crates/fluvio-version-manager/src/common/version_installer.rs
> fix: fvm rename fallback

- .github/workflows/publish.yml
workflow_run does not trigger w/ a branches spec (maybe?)
> chore: ci, publish.yml remove branches

- .github/workflows/cd_dev.yaml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- tests/upgrade-test.sh
due to merge queue update, get really about sequencing this sets up a fix for publish running on failed CI.yml and CD_Dev running for a failed publish
> chore: ci, switch ci->publish->cd_dev to repo_dispatch

- Cargo.lock
- crates/fluvio-protocol-derive/Cargo.toml
- crates/fluvio-protocol-derive/src/ast/container.rs
- crates/fluvio-protocol-derive/src/ast/enum.rs
- crates/fluvio-protocol-derive/src/ast/prop.rs
- crates/fluvio-protocol-derive/src/util.rs
- crates/fluvio-spu-schema/Cargo.toml
- crates/fluvio-spu-schema/src/produce/request.rs
> Revert "Updating fluvio-protocol-derive crate from syn1 to syn2"

- crates/fluvio-version-manager/src/common/version_directory.rs
> fix: macos remove binaries before replacing

- Cargo.lock
- Cargo.toml
- crates/fluvio-smartengine/Cargo.toml
- crates/fluvio-smartengine/src/engine/wasmtime/state.rs
update third party dep
update wasmtime to 15.0
> chore: update dep

- crates/fluvio-sc/src/controllers/topics/reducer.rs
`TopicReducer` can start acting while partitions are not loaded to the store yet. We are waiting for the initial change of partitions store before we process the new topic state.
> fix: topic reducer should wait for partitions sync

- .github/workflows/cd_dev.yaml
- .github/workflows/cd_dev_mac.yaml
- .github/workflows/cd_release.yml
- .github/workflows/ci.yml
- .github/workflows/connector-publish.yml
- .github/workflows/hourly.yml
- .github/workflows/smartmodule-publish.yml
- actions/action-install-fluvio-cluster.sh
- dev-tools/smartmodule.Dockerfile
- makefiles/release.mk
- tests/cli/test_helper/fluvio_dev.bash
- tests/fluvio-validate-release.sh
- tests/upgrade-test.sh
Provide the `ctx` query param for CI related installations
> chore: use `ctx` ci for installations

- Cargo.lock
- crates/fluvio-socket/Cargo.toml
- crates/fluvio-socket/build.rs
- crates/fluvio/Cargo.toml
- crates/fluvio/build.rs
- crates/fluvio/src/fluvio.rs
Attempt to fix: https://github.com/infinyon/fluvio/issues/3787
> build: don't require git to build fluvio

- README.md
> Address some typos and grammar issues in README

- Cargo.lock
- crates/fluvio-channel-cli/Cargo.toml
- crates/fluvio/Cargo.toml
- crates/fluvio/src/admin.rs
- crates/fluvio/src/lib.rs
- docs: consumer doc fix
- docs: add admin.delete example
> docs: small updates to admin::delete and consumer docs

- crates/fluvio-cluster/src/check/mod.rs
> fix: fluvio cluster start, improve err message when cluster still running

- .github/workflows/publish.yml
only publish if artifacts are avaialable
> chore: ci, fix release

- crates/fluvio-hub-util/src/hubaccess.rs
needs hub server update before this will work.
Smartmodule and connector list and download should work w/o requiring fluvio cloud login
> fix: relax hub access login requirements

- .github/workflows/cd_dev.yaml
- .github/workflows/ci.yml
- .github/workflows/ci_mac.yaml
- .github/workflows/publish.yml
- crates/fluvio-storage/src/file.rs
- chore: ci, stability improvement (a little bit of an experiment: intermittent slow fs sync on gh causing intermittent failures?)
- chore: ci, update deprecated actions
- chore: ci, align sha inconsistencies
> chore: ci stability improvements

- crates/fluvio-cluster/src/charts/chart.rs
- crates/fluvio-cluster/src/charts/location.rs
- crates/fluvio-cluster/src/check/mod.rs
- crates/fluvio-cluster/src/cli/check.rs
- crates/fluvio-cluster/src/cli/delete.rs
- crates/fluvio-cluster/src/cli/diagnostics.rs
- crates/fluvio-cluster/src/cli/mod.rs
- crates/fluvio-cluster/src/cli/shutdown.rs
- crates/fluvio-cluster/src/cli/spu/display.rs
- crates/fluvio-cluster/src/cli/spu/register.rs
- crates/fluvio-cluster/src/cli/spu/unregister.rs
- crates/fluvio-cluster/src/cli/start/local.rs
- crates/fluvio-cluster/src/cli/start/sys.rs
- crates/fluvio-cluster/src/cli/status.rs
- crates/fluvio-cluster/src/cli/util.rs
- crates/fluvio-cluster/src/delete.rs
- crates/fluvio-cluster/src/lib.rs
- crates/fluvio-cluster/src/progress.rs
- crates/fluvio-cluster/src/runtime/local/mod.rs
- crates/fluvio-cluster/src/runtime/local/sc.rs
- crates/fluvio-cluster/src/start/k8.rs
- crates/fluvio-cluster/src/start/local.rs
This is a PR to reduce specialized errors, using the `anyhow` library.
https://github.com/infinyon/fluvio/issues/3541
> chore: remove unnecessary specialized errors

- Cargo.lock
- crates/fluvio-cli-common/src/user_input.rs
- rust-toolchain.toml
> chore: update deps

- Cargo.lock
- crates/fluvio-protocol/Cargo.toml
- crates/fluvio-protocol/src/link/error_code.rs
- crates/fluvio-spu/src/core/global_context.rs
- crates/fluvio-spu/src/replication/leader/replica_state.rs
- crates/fluvio-spu/src/replication/test.rs
- crates/fluvio-spu/src/services/public/stream_fetch.rs
- crates/fluvio-spu/src/services/public/tests/stream_fetch.rs
- crates/fluvio-types/Cargo.toml
- crates/fluvio-types/src/event.rs
Here's the beginning of an implementation to disconnect consumers when a topic is deleted. Of course, I'll need to add tests. Looking for feedback to get this PR up to standards :-)
> Exploratory impl of disconnecting on topic delete

- Cargo.lock
> chore: Run cargo update -p curve25519-dalek@4.1.1

- tests/cli/fluvio_smoke_tests/e2e-basic.bats
Add tests to the cli command `fluvio consume` with `--format` arguments.
This PR address #3118
I confirmed the test results in that file are all green :tada: 
```
❯ make cli-fluvio-smoke
...
bats ./tests/cli/fluvio_smoke_tests/e2e-basic.bats
e2e-basic.bats
/usr/bin/timeout
/usr/bin/timeout
✓ Create a topic
/usr/bin/timeout
✓ Produce message
/usr/bin/timeout
✓ Consume message
/usr/bin/timeout
✓ Consume message using format: key
/usr/bin/timeout
✓ Consume message using format: value
/usr/bin/timeout
✓ Consume message using format: offset
/usr/bin/timeout
✓ Consume message using format: partition
/usr/bin/timeout
✓ Consume message display timestamp using format: time
/usr/bin/timeout
✓ Consume with tail
/usr/bin/timeout
✓ Consume gzip message
/usr/bin/timeout
✓ Consume snappy message …
```
> :white_check_mark: tests for cli when consuming with format

- Cargo.lock
- crates/fluvio-protocol/Cargo.toml
- crates/fluvio-protocol/src/link/error_code.rs
- crates/fluvio-storage/src/replica.rs
- crates/fluvio-storage/src/segments.rs
> fix: use specialized error for evicted offset case

- crates/fluvio-benchmark/src/bin/fbm.rs
- crates/fluvio/src/fluvio.rs
- rust-toolchain.toml
- **chore: update to rust 1.77**
- **chore: cargo clippy 1.77 updates**
> chore: rust 1.77 toolchain update

- crates/fluvio-protocol/src/link/error_code.rs
- crates/fluvio-spu-schema/src/server/fetch_offset.rs
- crates/fluvio-spu-schema/src/server/stream_fetch.rs
- crates/fluvio/src/consumer/config.rs
- crates/fluvio/src/consumer/mod.rs
- crates/fluvio/src/consumer/offset.rs
- crates/fluvio/src/consumer/stream.rs
- crates/fluvio/src/fluvio.rs
- crates/fluvio/src/offset.rs
Added offset management to consumer API. The feature is marked as unstable until all components support it, and the feature is fully tested and documented.
> feat: added offset management to consumer api(unstable)

- crates/fluvio-sc/src/controllers/topics/controller.rs
- crates/fluvio-sc/src/init.rs
Added a control of Offset Topic existence on SC. The check is periodic, once in a minute.
The Offset topic has the following characteristics: 
- system=true
- retention 7days
- segment size 512 Mb
- partition size 2 Gb
> feat: added auto-creation of offsets topic

- Cargo.lock
- crates/fluvio-cli/Cargo.toml
- crates/fluvio-cli/src/client/consume/mod.rs
- crates/fluvio-cli/src/client/consumer/delete.rs
- crates/fluvio-cli/src/client/consumer/list.rs
- crates/fluvio-cli/src/client/consumer/mod.rs
- crates/fluvio-cli/src/client/mod.rs
- crates/fluvio-controlplane/src/lib.rs
- crates/fluvio-kv-storage/src/lib.rs
- crates/fluvio-kv-storage/src/log.rs
- crates/fluvio-sc/src/controllers/topics/controller.rs
- crates/fluvio-spu-schema/src/server/consumer_offset.rs
- crates/fluvio-spu/src/kv/consumer.rs
- crates/fluvio-spu/src/services/internal/fetch_consumer_offset_handler.rs
- crates/fluvio-spu/src/services/internal/update_consumer_offset_handler.rs
- crates/fluvio-spu/src/services/public/consumer_handler.rs
- crates/fluvio-spu/src/services/public/offset_request.rs
- crates/fluvio-types/src/defaults.rs
- crates/fluvio/src/consumer/mod.rs
- crates/fluvio/src/consumer/offset.rs
- crates/fluvio/src/fluvio.rs
Added consumer offsets to Fluvio CLI (under `unstable` feature):
List:
```bash
fluvio consumer list
``` 
Delete:
```bash
fluvio consumer delete c1
```
Consume:
```bash
fluvio consume my-topic --consumer c1
```
> feat: added consumer offset to cli

- .github/workflows/ci.yml
- Cargo.lock
- crates/fluvio-cli/Cargo.toml
- crates/fluvio-cli/src/client/consume/mod.rs
- crates/fluvio-cli/src/client/mod.rs
- crates/fluvio-protocol/src/link/error_code.rs
- crates/fluvio-test/src/tests/consumer_offsets/mod.rs
- crates/fluvio-test/src/tests/mod.rs
- crates/fluvio/src/consumer/config.rs
- crates/fluvio/src/fluvio.rs
- makefiles/test.mk
- tests/cli/fluvio_smoke_tests/consumer-offset.bats
- tests/cli/fluvio_smoke_tests/e2e-basic.bats
Added tests for consumers offset feature on Fluvio client, and on Fluvio CLI. 
Also, marked the feature as stable there.
> feat: mark consumers offset feature as stable

- crates/fluvio-cli/src/client/core/export.rs
- crates/fluvio-cli/src/client/edge/connect.rs
- crates/fluvio-cli/src/client/edge/mod.rs
- crates/fluvio-cli/src/client/edge/status.rs
- crates/fluvio-cli/src/client/mod.rs
- crates/fluvio-sc-schema/src/edge.rs
- crates/fluvio-sc/src/services/public_api/remote/register.rs
Needs:
Implementation of edge commands:
```
fluvio edge status
```
```
flvd edge connect --file edge.json
```
> feat: add edge commands 

- Cargo.lock
- Cargo.toml
- crates/fluvio-spu/src/core/leader_client.rs
- crates/fluvio/Cargo.toml
- crates/fluvio/src/admin.rs
- crates/fluvio/src/lib.rs
- crates/fluvio/src/spu.rs
- crates/fluvio/src/stream_socket.rs
New function to create streaming connection. 
Will be necessary for mirroring sc-to-sc connection.
Usage: https://github.com/infinyon/fluvio/blob/1c0022c1d1db2fd11197334e59a49f8eac959f53/crates/fluvio-sc/src/controllers/mirroring/controller.rs#L91
> chore: rename SpuSocket to StreamSocket

- Cargo.lock
- crates/fluvio-cli/src/install/opts.rs
- crates/fluvio-hub-util/Cargo.toml
- crates/fluvio-hub-util/src/cmd/mod.rs
- crates/fluvio-hub-util/src/fvm/api/client.rs
- crates/fluvio-hub-util/src/fvm/api/download.rs
- crates/fluvio-hub-util/src/htclient.rs
- crates/fluvio-hub-util/src/hubaccess.rs
- crates/fluvio-hub-util/src/utils.rs
- crates/fluvio-hub-util/tests/hub_package_meta_rw_test.yaml
- crates/fluvio/Cargo.toml
- **fix(fuvio-hub-util): upadate http client, better client isolation**
- **fix: fluvio-hub-util, replace htclient w/ ureq**
> fix: cdk/smdk publish, fluvio-hub-util

- crates/fluvio-controlplane-metadata/src/mirroring/mod.rs
- crates/fluvio-controlplane-metadata/src/partition/spec.rs
- crates/fluvio-controlplane-metadata/src/topic/spec.rs
- crates/fluvio-sc/src/controllers/mirroring/controller.rs
- crates/fluvio-sc/src/controllers/topics/policy.rs
- crates/fluvio-sc/src/services/public_api/mirroring/connect.rs
- k8-util/helm/fluvio-sys/Chart.yaml
- k8-util/helm/fluvio-sys/templates/crd_partition.yaml
- k8-util/helm/fluvio-sys/templates/crd_topic.yaml
Better to send the spu_endpoint from home instead try to get it later from remote.
> chore: add endpoint field in mirror

- .github/actions/dl-smdk/action.yml
- .github/workflows/ci.yml
- Cargo.lock
- Makefile
- crates/fluvio-smartengine/Cargo.toml
- crates/fluvio-smartengine/src/engine/fixture.rs
- crates/fluvio-spu/src/services/public/tests/mod.rs
- smartmodule/cargo_template/README.md
- smartmodule/examples/Makefile
- smartmodule/regex-filter/Makefile
- tests/cli/fluvio_smoke_tests/e2e-smartmodule-basic.bats
- tests/cli/fluvio_smoke_tests/producer-smartmodule.bats
- tests/cli/fluvio_smoke_tests/topic-basic.bats
smartmodule/examples and regex-filter
> chore: use smdk artifact for ci tests

- crates/fluvio-sc/src/controllers/mirroring/controller.rs
- tests/cli/mirroring_smoke_tests/e2e/fluvio-core.bats
This PR is for deleting remote topics when delete them on home.
Needs:
> feat: deleting remote topics when delete them on home.

- Cargo.lock
- crates/fluvio-cluster/Cargo.toml
- crates/fluvio-cluster/src/cli/delete.rs
- crates/fluvio-spu/Makefile
- makefiles/test.mk
- tests/cli/cli-platform-cross-version.bats
- tests/cli/fluvio_smoke_tests/non-concurrent/cluster-delete.bats
- tls/Makefile
Adds prompt when a user tries to delete a cluster.
Related: #3493
> feat(fluvio-cluster): prompt when deleting cluster

- crates/fluvio-controlplane-metadata/src/mirroring/mod.rs
- crates/fluvio-controlplane-metadata/src/partition/spec.rs
- crates/fluvio-controlplane-metadata/src/topic/spec.rs
- crates/fluvio-sc/src/controllers/mirroring/controller.rs
- crates/fluvio-sc/src/controllers/topics/policy.rs
- crates/fluvio-sc/src/services/public_api/mirroring/connect.rs
- crates/fluvio-spu/src/mirroring/remote/controller.rs
- crates/fluvio-spu/src/mirroring/test/fixture.rs
- crates/fluvio-spu/src/mirroring/test/integration.rs
- k8-util/helm/fluvio-sys/Chart.yaml
- k8-util/helm/fluvio-sys/templates/crd_partition.yaml
- k8-util/helm/fluvio-sys/templates/crd_topic.yaml
> feat: add sni prefix on spu to spu

- crates/smartmodule-development-kit/src/generate.rs
- crates/smartmodule-development-kit/src/publish.rs
Moves group validation from generation phase to publish phase.
> fix(smdk): post-pone group ownership check on `generate`

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- crates/fluvio-compression/Cargo.toml
- crates/fluvio-compression/src/lib.rs
- crates/fluvio-protocol/Cargo.toml
- crates/fluvio-protocol/src/record/batch.rs
- crates/fluvio/Cargo.toml
- crates/fluvio/src/producer/config.rs
- crates/fluvio/src/producer/memory_batch.rs
- crates/fluvio/src/producer/mod.rs
Keep compression on by default, but allow it to be turned off with `--no-default-features`
> Feature guard compression

- DEVELOPER.md
- README.md
Updates `DEVELOPER` guide with most recent changes on how to run Fluvio for development,
as well as taking advantage of formatting improvements offered by GitHub such as annotations, callouts and keyboard markdown.
Split command examples so users can copy the command without including the output.
Here is a rendered version: https://github.com/infinyon/fluvio/blob/chore/developer-md/DEVELOPER.md#inlining-helm-chart
> chore(docs): update `DEVELOPER.md`

- rfc/add-partition.md
Related: https://github.com/infinyon/fluvio/issues/3843
> docs: add partition prd

- crates/fluvio-cli/src/client/topic/add_partition.rs
- crates/fluvio-cli/src/client/topic/mod.rs
- crates/fluvio-protocol/src/link/error_code.rs
- crates/fluvio-sc/src/controllers/scheduler/partition.rs
- crates/fluvio-sc/src/controllers/topics/policy.rs
- crates/fluvio-sc/src/controllers/topics/reducer.rs
- crates/fluvio-sc/src/services/public_api/topic/mod.rs
- crates/fluvio-sc/src/services/public_api/topic/update/add_partition.rs
- crates/fluvio-sc/src/services/public_api/topic/update/mod.rs
- crates/fluvio-sc/src/services/public_api/update.rs
- tests/cli/fluvio_smoke_tests/add-partitions.bats
> feat: add partitions

- crates/fluvio-sc/src/k8/objects/spg_group.rs
- crates/fluvio-spu/src/replication/follower/controller.rs
- crates/fluvio-spu/src/services/internal/fetch_stream_request.rs
- crates/fluvio-spu/src/services/internal/service_impl.rs
Related: https://github.com/infinyon/fluvio/issues/4084
> fix: spu connections on kubernetes

- crates/fluvio-cli/src/client/topic/add_mirror.rs
- crates/fluvio-cli/src/client/topic/create.rs
- crates/fluvio-cli/src/client/topic/mod.rs
- crates/fluvio-controlplane-metadata/src/mirror/spec.rs
- crates/fluvio-controlplane-metadata/src/topic/spec.rs
- crates/fluvio-controlplane-metadata/src/topic/update.rs
- crates/fluvio-protocol/src/link/error_code.rs
- crates/fluvio-sc-schema/src/lib.rs
- crates/fluvio-sc/src/services/public_api/topic/update/add_mirror.rs
- crates/fluvio-sc/src/services/public_api/topic/update/mod.rs
- tests/cli/mirroring_smoke_tests/mirror-topic.bats
- tests/cli/mirroring_smoke_tests/remote.bats
This PR must allow these commands:
```
fluvio remote register edge1
fluvio topic create mirror-topic --mirror
fluvio topic add-mirror mirror-topic edge1
```
Related: https://github.com/infinyon/fluvio/issues/4039
> feat: add mirror remote

- crates/fluvio-storage/src/replica.rs
Related: https://github.com/infinyon/fluvio/issues/4100
> fix: load replica size

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- RELEASE.md
- crates/fluvio/README.md
- examples/docker-compose/README.md
- smartmodule/cargo_template/README.md
- **fix: README.md links**
- **fix: other *.md links to fluvio.io docs**
> fix: fluvio.io doc linkss from various README.md and other docs

- rfc/add-partition.md
- rfc/materialize_view.md
- rfc/offset-management.md
> chore: fix typos

- crates/cdk/src/build.rs
map to more supportable arch by default for builds, mapping does not apply if a specific `--target` flag is specified
follow on: --cloud flag build optimizations for easier building for cloud run connectors
> fix: cdk use preferred target for compatibility for default build target

- Cargo.lock
- crates/fluvio-cli/src/profile/export.rs
- crates/fluvio-extension-common/Cargo.toml
- crates/fluvio-extension-common/src/output/mod.rs
- crates/fluvio-extension-common/src/output/serde.rs
Related: #4166 
- Implements exporting profile in toml format
- Makes toml format default when exporting
> fix: implement profile export toml and make it default option

- .github/workflows/weekly.yml
- makefiles/test.mk
- tests/local-resume-test.sh
Example: https://github.com/infinyon/fluvio/actions/runs/10819913131/job/30018821783?pr=4176
> chore: add weekly ci

- .github/workflows/ci.yml
- crates/fluvio-cli/src/profile/export.rs
- makefiles/test.mk
- tests/cli/fluvio_smoke_tests/profile-export.bats
- tests/cli/test_helper/tools_check.bash
Fixes https://github.com/infinyon/fluvio/issues/4166
Add test and fix export format for toml to full config file
> fix: profile export, full config, add cli test

- crates/fluvio-hub-util/src/fvm/api/client.rs
Makes FVM context aware by using the `INFINYON_CI_CONTEXT` env var.
> feat(fvm): support for infinyon ci context

- Cargo.lock
- crates/fluvio-compression/Cargo.toml
- crates/fluvio-compression/src/lib.rs
- crates/fluvio-types/Cargo.toml
- crates/fluvio-types/src/compression.rs
- crates/fluvio-types/src/lib.rs
Introduces `Compression` to fluvio types
> feat(types): introduce `Compression` to `fluvio-types`

- crates/fluvio-cli/src/client/topic/create.rs
- tests/cli/fluvio_smoke_tests/topic-basic.bats
Related: https://github.com/infinyon/fluvio/issues/4228
```
$ fluvio topic create my-test --system
or
$ fluvio topic create my-test --s
```
> feat: create system topic

- examples/docker-compose/README.md
Related: https://github.com/infinyon/fluvio/issues/4232
> doc: typo about fluvio topic in docker examples

- crates/fluvio-cli/src/client/produce/mod.rs
- crates/fluvio/src/fluvio.rs
- tests/cli/mirroring_smoke_tests/e2e/fluvio-core.bats
Similar to https://github.com/infinyon/fluvio/pull/4241 but for mirrors.
`$ fluvio produce --mirror <mirror_name> my__topic`
or 
`$ fluvio produce -m <mirror_name> my__topic`
> feat: support producing by mirror

- .github/workflows/cd_dev.yaml
- tests/cli/cli-platform-cross-version.bats
- tests/cli/test_helper/fluvio_dev.bash
Make cli-platform-cross-version-test start the cluster and cli, not the CI.
Also will fix cd dev.
> chore: dev cd using right fluvio binary

- crates/fluvio/src/consumer/mod.rs
Reference: https://github.com/infinyon/fluvio/issues/4267#issuecomment-2489354987
> chore: un-deprecate stream_batches_with_config

- crates/fluvio-smartengine/Cargo.toml
- crates/fluvio-smartengine/src/transformation.rs
- crates/fluvio-smartengine/testdata/transformation/full.yaml
Updates versions for dependencies in transforms code.
> chore: update versions for refs

- crates/cdk/src/deploy.rs
- tests/cli/cdk_smoke_tests/cdk-multi-deploy.bats
Related: https://github.com/infinyon/fluvio/issues/4289
> fix: not allow duplicated connectors

- Cargo.lock
- Cargo.toml
- crates/fluvio-cli/src/client/hub/smartmodule/list.rs
- crates/fluvio-extension-common/Cargo.toml
- crates/fluvio-extension-common/src/common/mod.rs
- crates/fluvio-extension-common/src/common/time.rs
- crates/fluvio-hub-util/src/cmd/list.rs
Provides a `Released` column for both commands:
- `fluvio hub sm list`
- `fluvio hub conn list`
> feat(cli): format release date as time expression

- Cargo.lock
- crates/fluvio-hub-protocol/src/infinyon_tok.rs
- crates/fluvio-hub-util/src/hubaccess.rs
fix some cases where hub remote was not aligned as expected to credentials
> fix: multi-org token remote

- connector/docker/.gitignore
- connector/docker/Dockerfile
- connector/docker/Makefile
- connector/docker/README.md
- connector/docker/connector.yaml
> connector: provide sample Dockerfile

- crates/cargo-builder/src/package.rs
- dev-tools/smartmodule.Dockerfile
- rust-toolchain.toml
- smartmodule/cargo_template/README.md
- smartmodule/examples/.cargo/config.toml
> chore: update Rust to `1.84.0`

- crates/fluvio-benchmark/src/benchmark_driver.rs
- crates/fluvio-benchmark/src/cli.rs
- crates/fluvio-benchmark/src/config/config_matrix.rs
- crates/fluvio-benchmark/src/config/cross.rs
- crates/fluvio-benchmark/src/config/mod.rs
- crates/fluvio-benchmark/src/producer_benchmark.rs
- crates/fluvio-benchmark/src/producer_worker.rs
- crates/fluvio-benchmark/src/stats_collector.rs
available commands:
```
fluvio bench -- will use default matrix
fluvio bench matrix -- will use default matrix
fluvio bench matrix --config <path>
fluvio bench producer
```
> feat: add strategy config to fluvio benchmark

- crates/fluvio/src/producer/config.rs
resolves #4318.   This will reduce default latency
> config: change default linger to be 0

- Cargo.lock
- Cargo.toml
- crates/cdk/src/deploy.rs
- crates/fluvio-cluster/src/check/mod.rs
- crates/fluvio-cluster/src/cli/diagnostics.rs
- crates/fluvio-cluster/src/process/mod.rs
- crates/fluvio-test/src/main.rs
upgrade fluvio-aio to 0.7.1 and update dep
> chore: more update dep

- Cargo.lock
- Cargo.toml
- crates/fluvio/src/producer/partitioning.rs
- examples/partitioning-simple/Cargo.toml
- examples/partitioning-simple/src/lib.rs
Example of writing custom partitioning
> example:  custom partitioning

- Cargo.lock
- Cargo.toml
- connector/sink-test-connector/src/main.rs
- crates/fluvio-cli/src/client/consume/mod.rs
- crates/fluvio-test/src/tests/consumer_offsets/mod.rs
- crates/fluvio/Cargo.toml
- crates/fluvio/src/consumer/stream.rs
- crates/fluvio/src/fluvio.rs
- rfc/offset-management.md
Needed for: https://github.com/infinyon/fluvio/pull/4394
> chore: make offset_commit async

- crates/cdk/src/generate.rs
- crates/fluvio/src/consumer/retry.rs
- crates/fluvio/src/producer/accumulator.rs
- crates/fluvio/src/producer/config.rs
- crates/smartmodule-development-kit/src/generate.rs
Solves: https://github.com/infinyon/fluvio/issues/4355
> docs: add description to producer record callback

- crates/cdk/src/hub.rs
- crates/cdk/src/publish.rs
- crates/cdk/src/utils.rs
- crates/fluvio-cli/src/client/hub/smartmodule/mod.rs
- crates/fluvio-hub-util/src/cmd/list.rs
> fix: cdk, additional validation on `cdk publish`

- crates/fluvio-controlplane-metadata/src/topic/deduplication.rs
Should solve https://github.com/infinyon/fluvio/issues/4282
> chore: make dedup count required

- Cargo.lock
- crates/fluvio-test/src/tests/reconnection/mod.rs
- crates/fluvio-types/Cargo.toml
- crates/fluvio-types/src/defaults.rs
- crates/fluvio/src/consumer/retry.rs
- crates/fluvio/src/producer/partition_producer.rs
Should solve: https://github.com/infinyon/fluvio/issues/4421
> fix: reconnect producer when spu is down

- crates/fluvio-cluster/src/cli/start/k8.rs
- crates/fluvio-cluster/src/cli/start/mod.rs
- crates/fluvio-cluster/src/lib.rs
- crates/fluvio-cluster/src/start/k8.rs
- crates/fluvio-test-util/setup/environment/k8.rs
Resolves https://github.com/infinyon/fluvio/issues/4439
> feat: make SPG creation optional in crate API

- crates/fluvio-spu/src/core/global_context.rs
- crates/fluvio-spu/src/services/public/consumer_handler.rs
- tests/cli/fluvio_smoke_tests/consumer-offset.bats
Should solve: https://github.com/infinyon/fluvio/issues/4436 and https://github.com/infinyon/fluvio/issues/4308
> fix: delete consumer after topic delete

- crates/fluvio-cli/src/client/consume/record_format.rs
- crates/fluvio/src/fluvio.rs
> fix: return tls cluster connect error when built w/o tls

- crates/fluvio/src/lib.rs
fixes https://github.com/infinyon/fluvio/issues/4467
> fix: re-export PartitionId from fluvio package.

- Cargo.toml
- rust-toolchain.toml
- smartmodule/examples/Cargo.lock
update rust toolchain to 1.86 and related dep
> chore: update toolchain and dep

- Cargo.lock
- Cargo.toml
- crates/fluvio-protocol/Cargo.toml
- crates/fluvio-protocol/src/record/data.rs
- crates/fluvio/Cargo.toml
- crates/fluvio/src/consumer/config.rs
- crates/fluvio/src/consumer/mod.rs
- crates/fluvio/src/consumer/retry.rs
https://github.com/infinyon/fluvio/issues/4514
> fix: offset evicted on retry

- crates/fluvio-storage/src/mut_records.rs
Should solve: https://github.com/infinyon/fluvio/issues/4524
We're not calling `std::mem::forget` on write_all error cases. So we're having double free problems. 
Now consumer works even on out of storage state.
> fix: prevent double free on storage error

- crates/fluvio-controlplane-metadata/src/partition/status.rs
- crates/fluvio-sc/src/controllers/partitions/reducer.rs
Fix https://github.com/infinyon/fluvio/issues/4528
> fix: OutOfSpace partition status returning to online

- Cargo.lock
- Cargo.toml
> chore: downgrade openssl

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- release-tools/check-crate-version/src/main.rs
fix the check crate ci as now we're using workspace version.
> fix: check crate workspace instead each crate

- Cargo.lock
- Cargo.toml
- crates/cdk/Cargo.toml
- crates/fluvio-auth/Cargo.toml
- crates/fluvio-auth/src/x509/authenticator.rs
- crates/fluvio-hub-util/Cargo.toml
- crates/fluvio-sc/Cargo.toml
- crates/fluvio-sc/src/cli.rs
- crates/fluvio-sc/src/start.rs
- crates/fluvio-spu/Cargo.toml
- crates/fluvio-spu/src/config/cli.rs
- crates/fluvio-spu/src/start.rs
- crates/fluvio/Cargo.toml
- crates/smartmodule-development-kit/Cargo.toml
- release-tools/check-crate-version/Cargo.toml
> chore: use rustls instead openssl
